/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.records;


import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.tables.AccountBalanceView;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountBalanceViewRecord extends UpdatableRecordImpl<AccountBalanceViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.account_balance_view.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.account_balance_view.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>account.account_balance_view.currency</code>.
     */
    public void setCurrency(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.account_balance_view.currency</code>.
     */
    public String getCurrency() {
        return (String) get(1);
    }

    /**
     * Setter for <code>account.account_balance_view.balance</code>.
     */
    public void setBalance(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.account_balance_view.balance</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>account.account_balance_view.reserved</code>.
     */
    public void setReserved(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.account_balance_view.reserved</code>.
     */
    public BigDecimal getReserved() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>account.account_balance_view.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.account_balance_view.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.account_balance_view.version</code>.
     */
    public void setVersion(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.account_balance_view.version</code>.
     */
    public Long getVersion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>account.account_balance_view.last_updated_at</code>.
     */
    public void setLastUpdatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.account_balance_view.last_updated_at</code>.
     */
    public OffsetDateTime getLastUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountBalanceViewRecord
     */
    public AccountBalanceViewRecord() {
        super(AccountBalanceView.ACCOUNT_BALANCE_VIEW);
    }

    /**
     * Create a detached, initialised AccountBalanceViewRecord
     */
    public AccountBalanceViewRecord(UUID accountId, String currency, BigDecimal balance, BigDecimal reserved, String status, Long version, OffsetDateTime lastUpdatedAt) {
        super(AccountBalanceView.ACCOUNT_BALANCE_VIEW);

        setAccountId(accountId);
        setCurrency(currency);
        setBalance(balance);
        setReserved(reserved);
        setStatus(status);
        setVersion(version);
        setLastUpdatedAt(lastUpdatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountBalanceViewRecord
     */
    public AccountBalanceViewRecord(org.girardsimon.wealthpay.account.jooq.tables.pojos.AccountBalanceView value) {
        super(AccountBalanceView.ACCOUNT_BALANCE_VIEW);

        if (value != null) {
            setAccountId(value.getAccountId());
            setCurrency(value.getCurrency());
            setBalance(value.getBalance());
            setReserved(value.getReserved());
            setStatus(value.getStatus());
            setVersion(value.getVersion());
            setLastUpdatedAt(value.getLastUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
