/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.tables.AccountSnapshot;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountSnapshotRecord extends UpdatableRecordImpl<AccountSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.account_snapshot.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.account_snapshot.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>account.account_snapshot.state</code>.
     */
    public void setState(JSONB value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.account_snapshot.state</code>.
     */
    public JSONB getState() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>account.account_snapshot.version</code>.
     */
    public void setVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.account_snapshot.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>account.account_snapshot.last_updated_at</code>.
     */
    public void setLastUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.account_snapshot.last_updated_at</code>.
     */
    public OffsetDateTime getLastUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>account.account_snapshot.schema_version</code>.
     */
    public void setSchemaVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.account_snapshot.schema_version</code>.
     */
    public Long getSchemaVersion() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountSnapshotRecord
     */
    public AccountSnapshotRecord() {
        super(AccountSnapshot.ACCOUNT_SNAPSHOT);
    }

    /**
     * Create a detached, initialised AccountSnapshotRecord
     */
    public AccountSnapshotRecord(UUID accountId, JSONB state, Long version, OffsetDateTime lastUpdatedAt, Long schemaVersion) {
        super(AccountSnapshot.ACCOUNT_SNAPSHOT);

        setAccountId(accountId);
        setState(state);
        setVersion(version);
        setLastUpdatedAt(lastUpdatedAt);
        setSchemaVersion(schemaVersion);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountSnapshotRecord
     */
    public AccountSnapshotRecord(org.girardsimon.wealthpay.account.jooq.tables.pojos.AccountSnapshot value) {
        super(AccountSnapshot.ACCOUNT_SNAPSHOT);

        if (value != null) {
            setAccountId(value.getAccountId());
            setState(value.getState());
            setVersion(value.getVersion());
            setLastUpdatedAt(value.getLastUpdatedAt());
            setSchemaVersion(value.getSchemaVersion());
            resetChangedOnNotNull();
        }
    }
}
