/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.records;


import java.time.OffsetDateTime;

import org.girardsimon.wealthpay.account.jooq.tables.OutboxCleanupLog;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutboxCleanupLogRecord extends TableRecordImpl<OutboxCleanupLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.outbox_cleanup_log.run_at</code>.
     */
    public void setRunAt(OffsetDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.run_at</code>.
     */
    public OffsetDateTime getRunAt() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.partitions_created</code>.
     */
    public void setPartitionsCreated(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.partitions_created</code>.
     */
    public Integer getPartitionsCreated() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.partitions_dropped</code>.
     */
    public void setPartitionsDropped(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.partitions_dropped</code>.
     */
    public Integer getPartitionsDropped() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.remaining_partitions</code>.
     */
    public void setRemainingPartitions(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.remaining_partitions</code>.
     */
    public Integer getRemainingPartitions() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.status</code>.
     */
    public void setStatus(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.started_at</code>.
     */
    public void setStartedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.completed_at</code>.
     */
    public void setCompletedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.completed_at</code>.
     */
    public OffsetDateTime getCompletedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.error_message</code>.
     */
    public void setErrorMessage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.error_message</code>.
     */
    public String getErrorMessage() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OutboxCleanupLogRecord
     */
    public OutboxCleanupLogRecord() {
        super(OutboxCleanupLog.OUTBOX_CLEANUP_LOG);
    }

    /**
     * Create a detached, initialised OutboxCleanupLogRecord
     */
    public OutboxCleanupLogRecord(OffsetDateTime runAt, Integer partitionsCreated, Integer partitionsDropped, Integer remainingPartitions, String status, OffsetDateTime startedAt, OffsetDateTime completedAt, String errorMessage) {
        super(OutboxCleanupLog.OUTBOX_CLEANUP_LOG);

        setRunAt(runAt);
        setPartitionsCreated(partitionsCreated);
        setPartitionsDropped(partitionsDropped);
        setRemainingPartitions(remainingPartitions);
        setStatus(status);
        setStartedAt(startedAt);
        setCompletedAt(completedAt);
        setErrorMessage(errorMessage);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OutboxCleanupLogRecord
     */
    public OutboxCleanupLogRecord(org.girardsimon.wealthpay.account.jooq.tables.pojos.OutboxCleanupLog value) {
        super(OutboxCleanupLog.OUTBOX_CLEANUP_LOG);

        if (value != null) {
            setRunAt(value.getRunAt());
            setPartitionsCreated(value.getPartitionsCreated());
            setPartitionsDropped(value.getPartitionsDropped());
            setRemainingPartitions(value.getRemainingPartitions());
            setStatus(value.getStatus());
            setStartedAt(value.getStartedAt());
            setCompletedAt(value.getCompletedAt());
            setErrorMessage(value.getErrorMessage());
            resetChangedOnNotNull();
        }
    }
}
