/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.tables.ProcessedReservations;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedReservationsRecord extends UpdatableRecordImpl<ProcessedReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.processed_reservations.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.processed_reservations.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>account.processed_reservations.transaction_id</code>.
     */
    public void setTransactionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.processed_reservations.transaction_id</code>.
     */
    public UUID getTransactionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>account.processed_reservations.reservation_id</code>.
     */
    public void setReservationId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.processed_reservations.reservation_id</code>.
     */
    public UUID getReservationId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>account.processed_reservations.phase</code>.
     */
    public void setPhase(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.processed_reservations.phase</code>.
     */
    public String getPhase() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.processed_reservations.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.processed_reservations.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessedReservationsRecord
     */
    public ProcessedReservationsRecord() {
        super(ProcessedReservations.PROCESSED_RESERVATIONS);
    }

    /**
     * Create a detached, initialised ProcessedReservationsRecord
     */
    public ProcessedReservationsRecord(UUID accountId, UUID transactionId, UUID reservationId, String phase, OffsetDateTime occurredAt) {
        super(ProcessedReservations.PROCESSED_RESERVATIONS);

        setAccountId(accountId);
        setTransactionId(transactionId);
        setReservationId(reservationId);
        setPhase(phase);
        setOccurredAt(occurredAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProcessedReservationsRecord
     */
    public ProcessedReservationsRecord(org.girardsimon.wealthpay.account.jooq.tables.pojos.ProcessedReservations value) {
        super(ProcessedReservations.PROCESSED_RESERVATIONS);

        if (value != null) {
            setAccountId(value.getAccountId());
            setTransactionId(value.getTransactionId());
            setReservationId(value.getReservationId());
            setPhase(value.getPhase());
            setOccurredAt(value.getOccurredAt());
            resetChangedOnNotNull();
        }
    }
}
