/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.tables.ProcessedTransactions;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedTransactionsRecord extends UpdatableRecordImpl<ProcessedTransactionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.processed_transactions.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.processed_transactions.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>account.processed_transactions.transaction_id</code>.
     */
    public void setTransactionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.processed_transactions.transaction_id</code>.
     */
    public UUID getTransactionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>account.processed_transactions.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.processed_transactions.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessedTransactionsRecord
     */
    public ProcessedTransactionsRecord() {
        super(ProcessedTransactions.PROCESSED_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised ProcessedTransactionsRecord
     */
    public ProcessedTransactionsRecord(UUID accountId, UUID transactionId, OffsetDateTime occurredAt) {
        super(ProcessedTransactions.PROCESSED_TRANSACTIONS);

        setAccountId(accountId);
        setTransactionId(transactionId);
        setOccurredAt(occurredAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProcessedTransactionsRecord
     */
    public ProcessedTransactionsRecord(org.girardsimon.wealthpay.account.jooq.tables.pojos.ProcessedTransactions value) {
        super(ProcessedTransactions.PROCESSED_TRANSACTIONS);

        if (value != null) {
            setAccountId(value.getAccountId());
            setTransactionId(value.getTransactionId());
            setOccurredAt(value.getOccurredAt());
            resetChangedOnNotNull();
        }
    }
}
