/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.routines;


import org.girardsimon.wealthpay.account.jooq.Account;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DbzPublicationIsCanonical extends AbstractRoutine<Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>account.dbz_publication_is_canonical.RETURN_VALUE</code>.
     */
    public static final Parameter<Boolean> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public DbzPublicationIsCanonical() {
        super("dbz_publication_is_canonical", Account.ACCOUNT, SQLDataType.BOOLEAN);

        setReturnParameter(RETURN_VALUE);
    }
}
