/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.routines;


import org.girardsimon.wealthpay.account.jooq.Account;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ManageOutboxPartitions extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>account.manage_outbox_partitions.retention_days</code>.
     */
    public static final Parameter<Integer> RETENTION_DAYS = Internal.createParameter("retention_days", SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("3"), SQLDataType.INTEGER)), true, false);

    /**
     * Create a new routine call instance
     */
    public ManageOutboxPartitions() {
        super("manage_outbox_partitions", Account.ACCOUNT);

        addInParameter(RETENTION_DAYS);
    }

    /**
     * Set the <code>retention_days</code> parameter IN value to the routine
     */
    public void setRetentionDays(Integer value) {
        setValue(RETENTION_DAYS, value);
    }
}
