/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountBalanceView implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID accountId;
    private String currency;
    private BigDecimal balance;
    private BigDecimal reserved;
    private String status;
    private Long version;
    private OffsetDateTime lastUpdatedAt;

    public AccountBalanceView() {}

    public AccountBalanceView(AccountBalanceView value) {
        this.accountId = value.accountId;
        this.currency = value.currency;
        this.balance = value.balance;
        this.reserved = value.reserved;
        this.status = value.status;
        this.version = value.version;
        this.lastUpdatedAt = value.lastUpdatedAt;
    }

    public AccountBalanceView(
        UUID accountId,
        String currency,
        BigDecimal balance,
        BigDecimal reserved,
        String status,
        Long version,
        OffsetDateTime lastUpdatedAt
    ) {
        this.accountId = accountId;
        this.currency = currency;
        this.balance = balance;
        this.reserved = reserved;
        this.status = status;
        this.version = version;
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * Getter for <code>account.account_balance_view.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>account.account_balance_view.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>account.account_balance_view.currency</code>.
     */
    public String getCurrency() {
        return this.currency;
    }

    /**
     * Setter for <code>account.account_balance_view.currency</code>.
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for <code>account.account_balance_view.balance</code>.
     */
    public BigDecimal getBalance() {
        return this.balance;
    }

    /**
     * Setter for <code>account.account_balance_view.balance</code>.
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * Getter for <code>account.account_balance_view.reserved</code>.
     */
    public BigDecimal getReserved() {
        return this.reserved;
    }

    /**
     * Setter for <code>account.account_balance_view.reserved</code>.
     */
    public void setReserved(BigDecimal reserved) {
        this.reserved = reserved;
    }

    /**
     * Getter for <code>account.account_balance_view.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>account.account_balance_view.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>account.account_balance_view.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>account.account_balance_view.version</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>account.account_balance_view.last_updated_at</code>.
     */
    public OffsetDateTime getLastUpdatedAt() {
        return this.lastUpdatedAt;
    }

    /**
     * Setter for <code>account.account_balance_view.last_updated_at</code>.
     */
    public void setLastUpdatedAt(OffsetDateTime lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccountBalanceView other = (AccountBalanceView) obj;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.currency == null) {
            if (other.currency != null)
                return false;
        }
        else if (!this.currency.equals(other.currency))
            return false;
        if (this.balance == null) {
            if (other.balance != null)
                return false;
        }
        else if (!this.balance.equals(other.balance))
            return false;
        if (this.reserved == null) {
            if (other.reserved != null)
                return false;
        }
        else if (!this.reserved.equals(other.reserved))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.lastUpdatedAt == null) {
            if (other.lastUpdatedAt != null)
                return false;
        }
        else if (!this.lastUpdatedAt.equals(other.lastUpdatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.currency == null) ? 0 : this.currency.hashCode());
        result = prime * result + ((this.balance == null) ? 0 : this.balance.hashCode());
        result = prime * result + ((this.reserved == null) ? 0 : this.reserved.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.lastUpdatedAt == null) ? 0 : this.lastUpdatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountBalanceView (");

        sb.append(accountId);
        sb.append(", ").append(currency);
        sb.append(", ").append(balance);
        sb.append(", ").append(reserved);
        sb.append(", ").append(status);
        sb.append(", ").append(version);
        sb.append(", ").append(lastUpdatedAt);

        sb.append(")");
        return sb.toString();
    }
}
