/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountSnapshot implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID accountId;
    private JSONB state;
    private Long version;
    private OffsetDateTime lastUpdatedAt;

    public AccountSnapshot() {}

    public AccountSnapshot(AccountSnapshot value) {
        this.accountId = value.accountId;
        this.state = value.state;
        this.version = value.version;
        this.lastUpdatedAt = value.lastUpdatedAt;
    }

    public AccountSnapshot(
        UUID accountId,
        JSONB state,
        Long version,
        OffsetDateTime lastUpdatedAt
    ) {
        this.accountId = accountId;
        this.state = state;
        this.version = version;
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * Getter for <code>account.account_snapshot.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>account.account_snapshot.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>account.account_snapshot.state</code>.
     */
    public JSONB getState() {
        return this.state;
    }

    /**
     * Setter for <code>account.account_snapshot.state</code>.
     */
    public void setState(JSONB state) {
        this.state = state;
    }

    /**
     * Getter for <code>account.account_snapshot.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>account.account_snapshot.version</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>account.account_snapshot.last_updated_at</code>.
     */
    public OffsetDateTime getLastUpdatedAt() {
        return this.lastUpdatedAt;
    }

    /**
     * Setter for <code>account.account_snapshot.last_updated_at</code>.
     */
    public void setLastUpdatedAt(OffsetDateTime lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccountSnapshot other = (AccountSnapshot) obj;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.lastUpdatedAt == null) {
            if (other.lastUpdatedAt != null)
                return false;
        }
        else if (!this.lastUpdatedAt.equals(other.lastUpdatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.lastUpdatedAt == null) ? 0 : this.lastUpdatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountSnapshot (");

        sb.append(accountId);
        sb.append(", ").append(state);
        sb.append(", ").append(version);
        sb.append(", ").append(lastUpdatedAt);

        sb.append(")");
        return sb.toString();
    }
}
