/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutboxCleanupLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private OffsetDateTime runAt;
    private Integer partitionsCreated;
    private Integer partitionsDropped;
    private Integer remainingPartitions;

    public OutboxCleanupLog() {}

    public OutboxCleanupLog(OutboxCleanupLog value) {
        this.runAt = value.runAt;
        this.partitionsCreated = value.partitionsCreated;
        this.partitionsDropped = value.partitionsDropped;
        this.remainingPartitions = value.remainingPartitions;
    }

    public OutboxCleanupLog(
        OffsetDateTime runAt,
        Integer partitionsCreated,
        Integer partitionsDropped,
        Integer remainingPartitions
    ) {
        this.runAt = runAt;
        this.partitionsCreated = partitionsCreated;
        this.partitionsDropped = partitionsDropped;
        this.remainingPartitions = remainingPartitions;
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.run_at</code>.
     */
    public OffsetDateTime getRunAt() {
        return this.runAt;
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.run_at</code>.
     */
    public void setRunAt(OffsetDateTime runAt) {
        this.runAt = runAt;
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.partitions_created</code>.
     */
    public Integer getPartitionsCreated() {
        return this.partitionsCreated;
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.partitions_created</code>.
     */
    public void setPartitionsCreated(Integer partitionsCreated) {
        this.partitionsCreated = partitionsCreated;
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.partitions_dropped</code>.
     */
    public Integer getPartitionsDropped() {
        return this.partitionsDropped;
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.partitions_dropped</code>.
     */
    public void setPartitionsDropped(Integer partitionsDropped) {
        this.partitionsDropped = partitionsDropped;
    }

    /**
     * Getter for <code>account.outbox_cleanup_log.remaining_partitions</code>.
     */
    public Integer getRemainingPartitions() {
        return this.remainingPartitions;
    }

    /**
     * Setter for <code>account.outbox_cleanup_log.remaining_partitions</code>.
     */
    public void setRemainingPartitions(Integer remainingPartitions) {
        this.remainingPartitions = remainingPartitions;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OutboxCleanupLog other = (OutboxCleanupLog) obj;
        if (this.runAt == null) {
            if (other.runAt != null)
                return false;
        }
        else if (!this.runAt.equals(other.runAt))
            return false;
        if (this.partitionsCreated == null) {
            if (other.partitionsCreated != null)
                return false;
        }
        else if (!this.partitionsCreated.equals(other.partitionsCreated))
            return false;
        if (this.partitionsDropped == null) {
            if (other.partitionsDropped != null)
                return false;
        }
        else if (!this.partitionsDropped.equals(other.partitionsDropped))
            return false;
        if (this.remainingPartitions == null) {
            if (other.remainingPartitions != null)
                return false;
        }
        else if (!this.remainingPartitions.equals(other.remainingPartitions))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.runAt == null) ? 0 : this.runAt.hashCode());
        result = prime * result + ((this.partitionsCreated == null) ? 0 : this.partitionsCreated.hashCode());
        result = prime * result + ((this.partitionsDropped == null) ? 0 : this.partitionsDropped.hashCode());
        result = prime * result + ((this.remainingPartitions == null) ? 0 : this.remainingPartitions.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OutboxCleanupLog (");

        sb.append(runAt);
        sb.append(", ").append(partitionsCreated);
        sb.append(", ").append(partitionsDropped);
        sb.append(", ").append(remainingPartitions);

        sb.append(")");
        return sb.toString();
    }
}
