/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedTransactions implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID accountId;
    private UUID transactionId;
    private OffsetDateTime occurredAt;

    public ProcessedTransactions() {}

    public ProcessedTransactions(ProcessedTransactions value) {
        this.accountId = value.accountId;
        this.transactionId = value.transactionId;
        this.occurredAt = value.occurredAt;
    }

    public ProcessedTransactions(
        UUID accountId,
        UUID transactionId,
        OffsetDateTime occurredAt
    ) {
        this.accountId = accountId;
        this.transactionId = transactionId;
        this.occurredAt = occurredAt;
    }

    /**
     * Getter for <code>account.processed_transactions.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>account.processed_transactions.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>account.processed_transactions.transaction_id</code>.
     */
    public UUID getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>account.processed_transactions.transaction_id</code>.
     */
    public void setTransactionId(UUID transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for <code>account.processed_transactions.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }

    /**
     * Setter for <code>account.processed_transactions.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProcessedTransactions other = (ProcessedTransactions) obj;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!this.transactionId.equals(other.transactionId))
            return false;
        if (this.occurredAt == null) {
            if (other.occurredAt != null)
                return false;
        }
        else if (!this.occurredAt.equals(other.occurredAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.occurredAt == null) ? 0 : this.occurredAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessedTransactions (");

        sb.append(accountId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(occurredAt);

        sb.append(")");
        return sb.toString();
    }
}
