/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedReservations implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID accountId;
    private UUID transactionId;
    private UUID reservationId;
    private String phase;
    private OffsetDateTime occurredAt;

    public ProcessedReservations() {}

    public ProcessedReservations(ProcessedReservations value) {
        this.accountId = value.accountId;
        this.transactionId = value.transactionId;
        this.reservationId = value.reservationId;
        this.phase = value.phase;
        this.occurredAt = value.occurredAt;
    }

    public ProcessedReservations(
        UUID accountId,
        UUID transactionId,
        UUID reservationId,
        String phase,
        OffsetDateTime occurredAt
    ) {
        this.accountId = accountId;
        this.transactionId = transactionId;
        this.reservationId = reservationId;
        this.phase = phase;
        this.occurredAt = occurredAt;
    }

    /**
     * Getter for <code>account.processed_reservations.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>account.processed_reservations.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>account.processed_reservations.transaction_id</code>.
     */
    public UUID getTransactionId() {
        return this.transactionId;
    }

    /**
     * Setter for <code>account.processed_reservations.transaction_id</code>.
     */
    public void setTransactionId(UUID transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Getter for <code>account.processed_reservations.reservation_id</code>.
     */
    public UUID getReservationId() {
        return this.reservationId;
    }

    /**
     * Setter for <code>account.processed_reservations.reservation_id</code>.
     */
    public void setReservationId(UUID reservationId) {
        this.reservationId = reservationId;
    }

    /**
     * Getter for <code>account.processed_reservations.phase</code>.
     */
    public String getPhase() {
        return this.phase;
    }

    /**
     * Setter for <code>account.processed_reservations.phase</code>.
     */
    public void setPhase(String phase) {
        this.phase = phase;
    }

    /**
     * Getter for <code>account.processed_reservations.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }

    /**
     * Setter for <code>account.processed_reservations.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProcessedReservations other = (ProcessedReservations) obj;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.transactionId == null) {
            if (other.transactionId != null)
                return false;
        }
        else if (!this.transactionId.equals(other.transactionId))
            return false;
        if (this.reservationId == null) {
            if (other.reservationId != null)
                return false;
        }
        else if (!this.reservationId.equals(other.reservationId))
            return false;
        if (this.phase == null) {
            if (other.phase != null)
                return false;
        }
        else if (!this.phase.equals(other.phase))
            return false;
        if (this.occurredAt == null) {
            if (other.occurredAt != null)
                return false;
        }
        else if (!this.occurredAt.equals(other.occurredAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.transactionId == null) ? 0 : this.transactionId.hashCode());
        result = prime * result + ((this.reservationId == null) ? 0 : this.reservationId.hashCode());
        result = prime * result + ((this.phase == null) ? 0 : this.phase.hashCode());
        result = prime * result + ((this.occurredAt == null) ? 0 : this.occurredAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProcessedReservations (");

        sb.append(accountId);
        sb.append(", ").append(transactionId);
        sb.append(", ").append(reservationId);
        sb.append(", ").append(phase);
        sb.append(", ").append(occurredAt);

        sb.append(")");
        return sb.toString();
    }
}
