/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionDecision implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String idempotencyKey;
    private Long policyVersion;
    private String outcome;
    private String subjectType;
    private String[] nationalities;
    private String countryOfResidence;
    private String countryOfIncorporation;
    private OffsetDateTime decidedAt;
    private OffsetDateTime recordedAt;

    public AdmissionDecision() {}

    public AdmissionDecision(AdmissionDecision value) {
        this.id = value.id;
        this.idempotencyKey = value.idempotencyKey;
        this.policyVersion = value.policyVersion;
        this.outcome = value.outcome;
        this.subjectType = value.subjectType;
        this.nationalities = value.nationalities;
        this.countryOfResidence = value.countryOfResidence;
        this.countryOfIncorporation = value.countryOfIncorporation;
        this.decidedAt = value.decidedAt;
        this.recordedAt = value.recordedAt;
    }

    public AdmissionDecision(
        UUID id,
        String idempotencyKey,
        Long policyVersion,
        String outcome,
        String subjectType,
        String[] nationalities,
        String countryOfResidence,
        String countryOfIncorporation,
        OffsetDateTime decidedAt,
        OffsetDateTime recordedAt
    ) {
        this.id = id;
        this.idempotencyKey = idempotencyKey;
        this.policyVersion = policyVersion;
        this.outcome = outcome;
        this.subjectType = subjectType;
        this.nationalities = nationalities;
        this.countryOfResidence = countryOfResidence;
        this.countryOfIncorporation = countryOfIncorporation;
        this.decidedAt = decidedAt;
        this.recordedAt = recordedAt;
    }

    /**
     * Getter for <code>customer.admission_decision.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>customer.admission_decision.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>customer.admission_decision.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return this.idempotencyKey;
    }

    /**
     * Setter for <code>customer.admission_decision.idempotency_key</code>.
     */
    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    /**
     * Getter for <code>customer.admission_decision.policy_version</code>.
     */
    public Long getPolicyVersion() {
        return this.policyVersion;
    }

    /**
     * Setter for <code>customer.admission_decision.policy_version</code>.
     */
    public void setPolicyVersion(Long policyVersion) {
        this.policyVersion = policyVersion;
    }

    /**
     * Getter for <code>customer.admission_decision.outcome</code>.
     */
    public String getOutcome() {
        return this.outcome;
    }

    /**
     * Setter for <code>customer.admission_decision.outcome</code>.
     */
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    /**
     * Getter for <code>customer.admission_decision.subject_type</code>.
     */
    public String getSubjectType() {
        return this.subjectType;
    }

    /**
     * Setter for <code>customer.admission_decision.subject_type</code>.
     */
    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }

    /**
     * Getter for <code>customer.admission_decision.nationalities</code>.
     */
    public String[] getNationalities() {
        return this.nationalities;
    }

    /**
     * Setter for <code>customer.admission_decision.nationalities</code>.
     */
    public void setNationalities(String[] nationalities) {
        this.nationalities = nationalities;
    }

    /**
     * Getter for <code>customer.admission_decision.country_of_residence</code>.
     */
    public String getCountryOfResidence() {
        return this.countryOfResidence;
    }

    /**
     * Setter for <code>customer.admission_decision.country_of_residence</code>.
     */
    public void setCountryOfResidence(String countryOfResidence) {
        this.countryOfResidence = countryOfResidence;
    }

    /**
     * Getter for
     * <code>customer.admission_decision.country_of_incorporation</code>.
     */
    public String getCountryOfIncorporation() {
        return this.countryOfIncorporation;
    }

    /**
     * Setter for
     * <code>customer.admission_decision.country_of_incorporation</code>.
     */
    public void setCountryOfIncorporation(String countryOfIncorporation) {
        this.countryOfIncorporation = countryOfIncorporation;
    }

    /**
     * Getter for <code>customer.admission_decision.decided_at</code>.
     */
    public OffsetDateTime getDecidedAt() {
        return this.decidedAt;
    }

    /**
     * Setter for <code>customer.admission_decision.decided_at</code>.
     */
    public void setDecidedAt(OffsetDateTime decidedAt) {
        this.decidedAt = decidedAt;
    }

    /**
     * Getter for <code>customer.admission_decision.recorded_at</code>.
     */
    public OffsetDateTime getRecordedAt() {
        return this.recordedAt;
    }

    /**
     * Setter for <code>customer.admission_decision.recorded_at</code>.
     */
    public void setRecordedAt(OffsetDateTime recordedAt) {
        this.recordedAt = recordedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AdmissionDecision other = (AdmissionDecision) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.idempotencyKey == null) {
            if (other.idempotencyKey != null)
                return false;
        }
        else if (!this.idempotencyKey.equals(other.idempotencyKey))
            return false;
        if (this.policyVersion == null) {
            if (other.policyVersion != null)
                return false;
        }
        else if (!this.policyVersion.equals(other.policyVersion))
            return false;
        if (this.outcome == null) {
            if (other.outcome != null)
                return false;
        }
        else if (!this.outcome.equals(other.outcome))
            return false;
        if (this.subjectType == null) {
            if (other.subjectType != null)
                return false;
        }
        else if (!this.subjectType.equals(other.subjectType))
            return false;
        if (this.nationalities == null) {
            if (other.nationalities != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.nationalities, other.nationalities))
            return false;
        if (this.countryOfResidence == null) {
            if (other.countryOfResidence != null)
                return false;
        }
        else if (!this.countryOfResidence.equals(other.countryOfResidence))
            return false;
        if (this.countryOfIncorporation == null) {
            if (other.countryOfIncorporation != null)
                return false;
        }
        else if (!this.countryOfIncorporation.equals(other.countryOfIncorporation))
            return false;
        if (this.decidedAt == null) {
            if (other.decidedAt != null)
                return false;
        }
        else if (!this.decidedAt.equals(other.decidedAt))
            return false;
        if (this.recordedAt == null) {
            if (other.recordedAt != null)
                return false;
        }
        else if (!this.recordedAt.equals(other.recordedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.idempotencyKey == null) ? 0 : this.idempotencyKey.hashCode());
        result = prime * result + ((this.policyVersion == null) ? 0 : this.policyVersion.hashCode());
        result = prime * result + ((this.outcome == null) ? 0 : this.outcome.hashCode());
        result = prime * result + ((this.subjectType == null) ? 0 : this.subjectType.hashCode());
        result = prime * result + ((this.nationalities == null) ? 0 : Arrays.deepHashCode(this.nationalities));
        result = prime * result + ((this.countryOfResidence == null) ? 0 : this.countryOfResidence.hashCode());
        result = prime * result + ((this.countryOfIncorporation == null) ? 0 : this.countryOfIncorporation.hashCode());
        result = prime * result + ((this.decidedAt == null) ? 0 : this.decidedAt.hashCode());
        result = prime * result + ((this.recordedAt == null) ? 0 : this.recordedAt.hashCode());
        return result;
    }
}
