/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionDecisionMatch implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID decisionId;
    private Integer ordinal;
    private String restriction;
    private String connectingFactor;
    private String triggeringCountry;

    public AdmissionDecisionMatch() {}

    public AdmissionDecisionMatch(AdmissionDecisionMatch value) {
        this.decisionId = value.decisionId;
        this.ordinal = value.ordinal;
        this.restriction = value.restriction;
        this.connectingFactor = value.connectingFactor;
        this.triggeringCountry = value.triggeringCountry;
    }

    public AdmissionDecisionMatch(
        UUID decisionId,
        Integer ordinal,
        String restriction,
        String connectingFactor,
        String triggeringCountry
    ) {
        this.decisionId = decisionId;
        this.ordinal = ordinal;
        this.restriction = restriction;
        this.connectingFactor = connectingFactor;
        this.triggeringCountry = triggeringCountry;
    }

    /**
     * Getter for <code>customer.admission_decision_match.decision_id</code>.
     */
    public UUID getDecisionId() {
        return this.decisionId;
    }

    /**
     * Setter for <code>customer.admission_decision_match.decision_id</code>.
     */
    public void setDecisionId(UUID decisionId) {
        this.decisionId = decisionId;
    }

    /**
     * Getter for <code>customer.admission_decision_match.ordinal</code>.
     */
    public Integer getOrdinal() {
        return this.ordinal;
    }

    /**
     * Setter for <code>customer.admission_decision_match.ordinal</code>.
     */
    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * Getter for <code>customer.admission_decision_match.restriction</code>.
     */
    public String getRestriction() {
        return this.restriction;
    }

    /**
     * Setter for <code>customer.admission_decision_match.restriction</code>.
     */
    public void setRestriction(String restriction) {
        this.restriction = restriction;
    }

    /**
     * Getter for
     * <code>customer.admission_decision_match.connecting_factor</code>.
     */
    public String getConnectingFactor() {
        return this.connectingFactor;
    }

    /**
     * Setter for
     * <code>customer.admission_decision_match.connecting_factor</code>.
     */
    public void setConnectingFactor(String connectingFactor) {
        this.connectingFactor = connectingFactor;
    }

    /**
     * Getter for
     * <code>customer.admission_decision_match.triggering_country</code>.
     */
    public String getTriggeringCountry() {
        return this.triggeringCountry;
    }

    /**
     * Setter for
     * <code>customer.admission_decision_match.triggering_country</code>.
     */
    public void setTriggeringCountry(String triggeringCountry) {
        this.triggeringCountry = triggeringCountry;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AdmissionDecisionMatch other = (AdmissionDecisionMatch) obj;
        if (this.decisionId == null) {
            if (other.decisionId != null)
                return false;
        }
        else if (!this.decisionId.equals(other.decisionId))
            return false;
        if (this.ordinal == null) {
            if (other.ordinal != null)
                return false;
        }
        else if (!this.ordinal.equals(other.ordinal))
            return false;
        if (this.restriction == null) {
            if (other.restriction != null)
                return false;
        }
        else if (!this.restriction.equals(other.restriction))
            return false;
        if (this.connectingFactor == null) {
            if (other.connectingFactor != null)
                return false;
        }
        else if (!this.connectingFactor.equals(other.connectingFactor))
            return false;
        if (this.triggeringCountry == null) {
            if (other.triggeringCountry != null)
                return false;
        }
        else if (!this.triggeringCountry.equals(other.triggeringCountry))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.decisionId == null) ? 0 : this.decisionId.hashCode());
        result = prime * result + ((this.ordinal == null) ? 0 : this.ordinal.hashCode());
        result = prime * result + ((this.restriction == null) ? 0 : this.restriction.hashCode());
        result = prime * result + ((this.connectingFactor == null) ? 0 : this.connectingFactor.hashCode());
        result = prime * result + ((this.triggeringCountry == null) ? 0 : this.triggeringCountry.hashCode());
        return result;
    }
}
