/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionPolicy implements Serializable {

    private static final long serialVersionUID = 1L;

    private Boolean singleton;
    private Long version;

    public AdmissionPolicy() {}

    public AdmissionPolicy(AdmissionPolicy value) {
        this.singleton = value.singleton;
        this.version = value.version;
    }

    public AdmissionPolicy(
        Boolean singleton,
        Long version
    ) {
        this.singleton = singleton;
        this.version = version;
    }

    /**
     * Getter for <code>customer.admission_policy.singleton</code>.
     */
    public Boolean getSingleton() {
        return this.singleton;
    }

    /**
     * Setter for <code>customer.admission_policy.singleton</code>.
     */
    public void setSingleton(Boolean singleton) {
        this.singleton = singleton;
    }

    /**
     * Getter for <code>customer.admission_policy.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>customer.admission_policy.version</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AdmissionPolicy other = (AdmissionPolicy) obj;
        if (this.singleton == null) {
            if (other.singleton != null)
                return false;
        }
        else if (!this.singleton.equals(other.singleton))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.singleton == null) ? 0 : this.singleton.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }
}
