/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerAdmission implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID customerId;
    private UUID decisionId;
    private String outcome;
    private String subjectType;
    private OffsetDateTime linkedAt;

    public CustomerAdmission() {}

    public CustomerAdmission(CustomerAdmission value) {
        this.customerId = value.customerId;
        this.decisionId = value.decisionId;
        this.outcome = value.outcome;
        this.subjectType = value.subjectType;
        this.linkedAt = value.linkedAt;
    }

    public CustomerAdmission(
        UUID customerId,
        UUID decisionId,
        String outcome,
        String subjectType,
        OffsetDateTime linkedAt
    ) {
        this.customerId = customerId;
        this.decisionId = decisionId;
        this.outcome = outcome;
        this.subjectType = subjectType;
        this.linkedAt = linkedAt;
    }

    /**
     * Getter for <code>customer.customer_admission.customer_id</code>.
     */
    public UUID getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>customer.customer_admission.customer_id</code>.
     */
    public void setCustomerId(UUID customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>customer.customer_admission.decision_id</code>.
     */
    public UUID getDecisionId() {
        return this.decisionId;
    }

    /**
     * Setter for <code>customer.customer_admission.decision_id</code>.
     */
    public void setDecisionId(UUID decisionId) {
        this.decisionId = decisionId;
    }

    /**
     * Getter for <code>customer.customer_admission.outcome</code>.
     */
    public String getOutcome() {
        return this.outcome;
    }

    /**
     * Setter for <code>customer.customer_admission.outcome</code>.
     */
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    /**
     * Getter for <code>customer.customer_admission.subject_type</code>.
     */
    public String getSubjectType() {
        return this.subjectType;
    }

    /**
     * Setter for <code>customer.customer_admission.subject_type</code>.
     */
    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }

    /**
     * Getter for <code>customer.customer_admission.linked_at</code>.
     */
    public OffsetDateTime getLinkedAt() {
        return this.linkedAt;
    }

    /**
     * Setter for <code>customer.customer_admission.linked_at</code>.
     */
    public void setLinkedAt(OffsetDateTime linkedAt) {
        this.linkedAt = linkedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerAdmission other = (CustomerAdmission) obj;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.decisionId == null) {
            if (other.decisionId != null)
                return false;
        }
        else if (!this.decisionId.equals(other.decisionId))
            return false;
        if (this.outcome == null) {
            if (other.outcome != null)
                return false;
        }
        else if (!this.outcome.equals(other.outcome))
            return false;
        if (this.subjectType == null) {
            if (other.subjectType != null)
                return false;
        }
        else if (!this.subjectType.equals(other.subjectType))
            return false;
        if (this.linkedAt == null) {
            if (other.linkedAt != null)
                return false;
        }
        else if (!this.linkedAt.equals(other.linkedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.decisionId == null) ? 0 : this.decisionId.hashCode());
        result = prime * result + ((this.outcome == null) ? 0 : this.outcome.hashCode());
        result = prime * result + ((this.subjectType == null) ? 0 : this.subjectType.hashCode());
        result = prime * result + ((this.linkedAt == null) ? 0 : this.linkedAt.hashCode());
        return result;
    }
}
