/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID id;
    private String customerNumber;
    private String email;
    private String status;
    private OffsetDateTime registeredAt;
    private OffsetDateTime activatedAt;
    private String kind;
    private String givenName;
    private String middleName;
    private String familyName;
    private LocalDate dateOfBirth;
    private String gender;
    private String countryOfResidence;
    private String registeredName;
    private String registrationNumber;
    private String countryOfIncorporation;

    public Customer() {}

    public Customer(Customer value) {
        this.id = value.id;
        this.customerNumber = value.customerNumber;
        this.email = value.email;
        this.status = value.status;
        this.registeredAt = value.registeredAt;
        this.activatedAt = value.activatedAt;
        this.kind = value.kind;
        this.givenName = value.givenName;
        this.middleName = value.middleName;
        this.familyName = value.familyName;
        this.dateOfBirth = value.dateOfBirth;
        this.gender = value.gender;
        this.countryOfResidence = value.countryOfResidence;
        this.registeredName = value.registeredName;
        this.registrationNumber = value.registrationNumber;
        this.countryOfIncorporation = value.countryOfIncorporation;
    }

    public Customer(
        UUID id,
        String customerNumber,
        String email,
        String status,
        OffsetDateTime registeredAt,
        OffsetDateTime activatedAt,
        String kind,
        String givenName,
        String middleName,
        String familyName,
        LocalDate dateOfBirth,
        String gender,
        String countryOfResidence,
        String registeredName,
        String registrationNumber,
        String countryOfIncorporation
    ) {
        this.id = id;
        this.customerNumber = customerNumber;
        this.email = email;
        this.status = status;
        this.registeredAt = registeredAt;
        this.activatedAt = activatedAt;
        this.kind = kind;
        this.givenName = givenName;
        this.middleName = middleName;
        this.familyName = familyName;
        this.dateOfBirth = dateOfBirth;
        this.gender = gender;
        this.countryOfResidence = countryOfResidence;
        this.registeredName = registeredName;
        this.registrationNumber = registrationNumber;
        this.countryOfIncorporation = countryOfIncorporation;
    }

    /**
     * Getter for <code>customer.customer.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>customer.customer.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>customer.customer.customer_number</code>.
     */
    public String getCustomerNumber() {
        return this.customerNumber;
    }

    /**
     * Setter for <code>customer.customer.customer_number</code>.
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * Getter for <code>customer.customer.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>customer.customer.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>customer.customer.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>customer.customer.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>customer.customer.registered_at</code>.
     */
    public OffsetDateTime getRegisteredAt() {
        return this.registeredAt;
    }

    /**
     * Setter for <code>customer.customer.registered_at</code>.
     */
    public void setRegisteredAt(OffsetDateTime registeredAt) {
        this.registeredAt = registeredAt;
    }

    /**
     * Getter for <code>customer.customer.activated_at</code>.
     */
    public OffsetDateTime getActivatedAt() {
        return this.activatedAt;
    }

    /**
     * Setter for <code>customer.customer.activated_at</code>.
     */
    public void setActivatedAt(OffsetDateTime activatedAt) {
        this.activatedAt = activatedAt;
    }

    /**
     * Getter for <code>customer.customer.kind</code>.
     */
    public String getKind() {
        return this.kind;
    }

    /**
     * Setter for <code>customer.customer.kind</code>.
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * Getter for <code>customer.customer.given_name</code>.
     */
    public String getGivenName() {
        return this.givenName;
    }

    /**
     * Setter for <code>customer.customer.given_name</code>.
     */
    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }

    /**
     * Getter for <code>customer.customer.middle_name</code>.
     */
    public String getMiddleName() {
        return this.middleName;
    }

    /**
     * Setter for <code>customer.customer.middle_name</code>.
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    /**
     * Getter for <code>customer.customer.family_name</code>.
     */
    public String getFamilyName() {
        return this.familyName;
    }

    /**
     * Setter for <code>customer.customer.family_name</code>.
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    /**
     * Getter for <code>customer.customer.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return this.dateOfBirth;
    }

    /**
     * Setter for <code>customer.customer.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * Getter for <code>customer.customer.gender</code>.
     */
    public String getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>customer.customer.gender</code>.
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Getter for <code>customer.customer.country_of_residence</code>.
     */
    public String getCountryOfResidence() {
        return this.countryOfResidence;
    }

    /**
     * Setter for <code>customer.customer.country_of_residence</code>.
     */
    public void setCountryOfResidence(String countryOfResidence) {
        this.countryOfResidence = countryOfResidence;
    }

    /**
     * Getter for <code>customer.customer.registered_name</code>.
     */
    public String getRegisteredName() {
        return this.registeredName;
    }

    /**
     * Setter for <code>customer.customer.registered_name</code>.
     */
    public void setRegisteredName(String registeredName) {
        this.registeredName = registeredName;
    }

    /**
     * Getter for <code>customer.customer.registration_number</code>.
     */
    public String getRegistrationNumber() {
        return this.registrationNumber;
    }

    /**
     * Setter for <code>customer.customer.registration_number</code>.
     */
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    /**
     * Getter for <code>customer.customer.country_of_incorporation</code>.
     */
    public String getCountryOfIncorporation() {
        return this.countryOfIncorporation;
    }

    /**
     * Setter for <code>customer.customer.country_of_incorporation</code>.
     */
    public void setCountryOfIncorporation(String countryOfIncorporation) {
        this.countryOfIncorporation = countryOfIncorporation;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Customer other = (Customer) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.customerNumber == null) {
            if (other.customerNumber != null)
                return false;
        }
        else if (!this.customerNumber.equals(other.customerNumber))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.registeredAt == null) {
            if (other.registeredAt != null)
                return false;
        }
        else if (!this.registeredAt.equals(other.registeredAt))
            return false;
        if (this.activatedAt == null) {
            if (other.activatedAt != null)
                return false;
        }
        else if (!this.activatedAt.equals(other.activatedAt))
            return false;
        if (this.kind == null) {
            if (other.kind != null)
                return false;
        }
        else if (!this.kind.equals(other.kind))
            return false;
        if (this.givenName == null) {
            if (other.givenName != null)
                return false;
        }
        else if (!this.givenName.equals(other.givenName))
            return false;
        if (this.middleName == null) {
            if (other.middleName != null)
                return false;
        }
        else if (!this.middleName.equals(other.middleName))
            return false;
        if (this.familyName == null) {
            if (other.familyName != null)
                return false;
        }
        else if (!this.familyName.equals(other.familyName))
            return false;
        if (this.dateOfBirth == null) {
            if (other.dateOfBirth != null)
                return false;
        }
        else if (!this.dateOfBirth.equals(other.dateOfBirth))
            return false;
        if (this.gender == null) {
            if (other.gender != null)
                return false;
        }
        else if (!this.gender.equals(other.gender))
            return false;
        if (this.countryOfResidence == null) {
            if (other.countryOfResidence != null)
                return false;
        }
        else if (!this.countryOfResidence.equals(other.countryOfResidence))
            return false;
        if (this.registeredName == null) {
            if (other.registeredName != null)
                return false;
        }
        else if (!this.registeredName.equals(other.registeredName))
            return false;
        if (this.registrationNumber == null) {
            if (other.registrationNumber != null)
                return false;
        }
        else if (!this.registrationNumber.equals(other.registrationNumber))
            return false;
        if (this.countryOfIncorporation == null) {
            if (other.countryOfIncorporation != null)
                return false;
        }
        else if (!this.countryOfIncorporation.equals(other.countryOfIncorporation))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.customerNumber == null) ? 0 : this.customerNumber.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.registeredAt == null) ? 0 : this.registeredAt.hashCode());
        result = prime * result + ((this.activatedAt == null) ? 0 : this.activatedAt.hashCode());
        result = prime * result + ((this.kind == null) ? 0 : this.kind.hashCode());
        result = prime * result + ((this.givenName == null) ? 0 : this.givenName.hashCode());
        result = prime * result + ((this.middleName == null) ? 0 : this.middleName.hashCode());
        result = prime * result + ((this.familyName == null) ? 0 : this.familyName.hashCode());
        result = prime * result + ((this.dateOfBirth == null) ? 0 : this.dateOfBirth.hashCode());
        result = prime * result + ((this.gender == null) ? 0 : this.gender.hashCode());
        result = prime * result + ((this.countryOfResidence == null) ? 0 : this.countryOfResidence.hashCode());
        result = prime * result + ((this.registeredName == null) ? 0 : this.registeredName.hashCode());
        result = prime * result + ((this.registrationNumber == null) ? 0 : this.registrationNumber.hashCode());
        result = prime * result + ((this.countryOfIncorporation == null) ? 0 : this.countryOfIncorporation.hashCode());
        return result;
    }
}
