/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerNationality implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID customerId;
    private String kind;
    private String countryCode;

    public CustomerNationality() {}

    public CustomerNationality(CustomerNationality value) {
        this.customerId = value.customerId;
        this.kind = value.kind;
        this.countryCode = value.countryCode;
    }

    public CustomerNationality(
        UUID customerId,
        String kind,
        String countryCode
    ) {
        this.customerId = customerId;
        this.kind = kind;
        this.countryCode = countryCode;
    }

    /**
     * Getter for <code>customer.customer_nationality.customer_id</code>.
     */
    public UUID getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>customer.customer_nationality.customer_id</code>.
     */
    public void setCustomerId(UUID customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>customer.customer_nationality.kind</code>.
     */
    public String getKind() {
        return this.kind;
    }

    /**
     * Setter for <code>customer.customer_nationality.kind</code>.
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * Getter for <code>customer.customer_nationality.country_code</code>.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Setter for <code>customer.customer_nationality.country_code</code>.
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerNationality other = (CustomerNationality) obj;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.kind == null) {
            if (other.kind != null)
                return false;
        }
        else if (!this.kind.equals(other.kind))
            return false;
        if (this.countryCode == null) {
            if (other.countryCode != null)
                return false;
        }
        else if (!this.countryCode.equals(other.countryCode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.kind == null) ? 0 : this.kind.hashCode());
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        return result;
    }
}
