/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerStatusTransition implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID customerId;
    private Integer sequenceNo;
    private String fromStatus;
    private String toStatus;
    private OffsetDateTime occurredAt;
    private OffsetDateTime recordedAt;
    private String actor;
    private String reason;

    public CustomerStatusTransition() {}

    public CustomerStatusTransition(CustomerStatusTransition value) {
        this.customerId = value.customerId;
        this.sequenceNo = value.sequenceNo;
        this.fromStatus = value.fromStatus;
        this.toStatus = value.toStatus;
        this.occurredAt = value.occurredAt;
        this.recordedAt = value.recordedAt;
        this.actor = value.actor;
        this.reason = value.reason;
    }

    public CustomerStatusTransition(
        UUID customerId,
        Integer sequenceNo,
        String fromStatus,
        String toStatus,
        OffsetDateTime occurredAt,
        OffsetDateTime recordedAt,
        String actor,
        String reason
    ) {
        this.customerId = customerId;
        this.sequenceNo = sequenceNo;
        this.fromStatus = fromStatus;
        this.toStatus = toStatus;
        this.occurredAt = occurredAt;
        this.recordedAt = recordedAt;
        this.actor = actor;
        this.reason = reason;
    }

    /**
     * Getter for <code>customer.customer_status_transition.customer_id</code>.
     */
    public UUID getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>customer.customer_status_transition.customer_id</code>.
     */
    public void setCustomerId(UUID customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>customer.customer_status_transition.sequence_no</code>.
     */
    public Integer getSequenceNo() {
        return this.sequenceNo;
    }

    /**
     * Setter for <code>customer.customer_status_transition.sequence_no</code>.
     */
    public void setSequenceNo(Integer sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    /**
     * Getter for <code>customer.customer_status_transition.from_status</code>.
     */
    public String getFromStatus() {
        return this.fromStatus;
    }

    /**
     * Setter for <code>customer.customer_status_transition.from_status</code>.
     */
    public void setFromStatus(String fromStatus) {
        this.fromStatus = fromStatus;
    }

    /**
     * Getter for <code>customer.customer_status_transition.to_status</code>.
     */
    public String getToStatus() {
        return this.toStatus;
    }

    /**
     * Setter for <code>customer.customer_status_transition.to_status</code>.
     */
    public void setToStatus(String toStatus) {
        this.toStatus = toStatus;
    }

    /**
     * Getter for <code>customer.customer_status_transition.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }

    /**
     * Setter for <code>customer.customer_status_transition.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    /**
     * Getter for <code>customer.customer_status_transition.recorded_at</code>.
     */
    public OffsetDateTime getRecordedAt() {
        return this.recordedAt;
    }

    /**
     * Setter for <code>customer.customer_status_transition.recorded_at</code>.
     */
    public void setRecordedAt(OffsetDateTime recordedAt) {
        this.recordedAt = recordedAt;
    }

    /**
     * Getter for <code>customer.customer_status_transition.actor</code>.
     */
    public String getActor() {
        return this.actor;
    }

    /**
     * Setter for <code>customer.customer_status_transition.actor</code>.
     */
    public void setActor(String actor) {
        this.actor = actor;
    }

    /**
     * Getter for <code>customer.customer_status_transition.reason</code>.
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * Setter for <code>customer.customer_status_transition.reason</code>.
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerStatusTransition other = (CustomerStatusTransition) obj;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.sequenceNo == null) {
            if (other.sequenceNo != null)
                return false;
        }
        else if (!this.sequenceNo.equals(other.sequenceNo))
            return false;
        if (this.fromStatus == null) {
            if (other.fromStatus != null)
                return false;
        }
        else if (!this.fromStatus.equals(other.fromStatus))
            return false;
        if (this.toStatus == null) {
            if (other.toStatus != null)
                return false;
        }
        else if (!this.toStatus.equals(other.toStatus))
            return false;
        if (this.occurredAt == null) {
            if (other.occurredAt != null)
                return false;
        }
        else if (!this.occurredAt.equals(other.occurredAt))
            return false;
        if (this.recordedAt == null) {
            if (other.recordedAt != null)
                return false;
        }
        else if (!this.recordedAt.equals(other.recordedAt))
            return false;
        if (this.actor == null) {
            if (other.actor != null)
                return false;
        }
        else if (!this.actor.equals(other.actor))
            return false;
        if (this.reason == null) {
            if (other.reason != null)
                return false;
        }
        else if (!this.reason.equals(other.reason))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.sequenceNo == null) ? 0 : this.sequenceNo.hashCode());
        result = prime * result + ((this.fromStatus == null) ? 0 : this.fromStatus.hashCode());
        result = prime * result + ((this.toStatus == null) ? 0 : this.toStatus.hashCode());
        result = prime * result + ((this.occurredAt == null) ? 0 : this.occurredAt.hashCode());
        result = prime * result + ((this.recordedAt == null) ? 0 : this.recordedAt.hashCode());
        result = prime * result + ((this.actor == null) ? 0 : this.actor.hashCode());
        result = prime * result + ((this.reason == null) ? 0 : this.reason.hashCode());
        return result;
    }
}
