/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedRegistrations implements Serializable {

    private static final long serialVersionUID = 1L;

    private String idempotencyKey;
    private String fingerprint;
    private UUID customerId;
    private OffsetDateTime occurredAt;

    public ProcessedRegistrations() {}

    public ProcessedRegistrations(ProcessedRegistrations value) {
        this.idempotencyKey = value.idempotencyKey;
        this.fingerprint = value.fingerprint;
        this.customerId = value.customerId;
        this.occurredAt = value.occurredAt;
    }

    public ProcessedRegistrations(
        String idempotencyKey,
        String fingerprint,
        UUID customerId,
        OffsetDateTime occurredAt
    ) {
        this.idempotencyKey = idempotencyKey;
        this.fingerprint = fingerprint;
        this.customerId = customerId;
        this.occurredAt = occurredAt;
    }

    /**
     * Getter for <code>customer.processed_registrations.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return this.idempotencyKey;
    }

    /**
     * Setter for <code>customer.processed_registrations.idempotency_key</code>.
     */
    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    /**
     * Getter for <code>customer.processed_registrations.fingerprint</code>.
     */
    public String getFingerprint() {
        return this.fingerprint;
    }

    /**
     * Setter for <code>customer.processed_registrations.fingerprint</code>.
     */
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint;
    }

    /**
     * Getter for <code>customer.processed_registrations.customer_id</code>.
     */
    public UUID getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>customer.processed_registrations.customer_id</code>.
     */
    public void setCustomerId(UUID customerId) {
        this.customerId = customerId;
    }

    /**
     * Getter for <code>customer.processed_registrations.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }

    /**
     * Setter for <code>customer.processed_registrations.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ProcessedRegistrations other = (ProcessedRegistrations) obj;
        if (this.idempotencyKey == null) {
            if (other.idempotencyKey != null)
                return false;
        }
        else if (!this.idempotencyKey.equals(other.idempotencyKey))
            return false;
        if (this.fingerprint == null) {
            if (other.fingerprint != null)
                return false;
        }
        else if (!this.fingerprint.equals(other.fingerprint))
            return false;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.occurredAt == null) {
            if (other.occurredAt != null)
                return false;
        }
        else if (!this.occurredAt.equals(other.occurredAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.idempotencyKey == null) ? 0 : this.idempotencyKey.hashCode());
        result = prime * result + ((this.fingerprint == null) ? 0 : this.fingerprint.hashCode());
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.occurredAt == null) ? 0 : this.occurredAt.hashCode());
        return result;
    }
}
