/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RestrictedCountry implements Serializable {

    private static final long serialVersionUID = 1L;

    private String countryCode;
    private String restriction;
    private String connectingFactor;

    public RestrictedCountry() {}

    public RestrictedCountry(RestrictedCountry value) {
        this.countryCode = value.countryCode;
        this.restriction = value.restriction;
        this.connectingFactor = value.connectingFactor;
    }

    public RestrictedCountry(
        String countryCode,
        String restriction,
        String connectingFactor
    ) {
        this.countryCode = countryCode;
        this.restriction = restriction;
        this.connectingFactor = connectingFactor;
    }

    /**
     * Getter for <code>customer.restricted_country.country_code</code>.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Setter for <code>customer.restricted_country.country_code</code>.
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for <code>customer.restricted_country.restriction</code>.
     */
    public String getRestriction() {
        return this.restriction;
    }

    /**
     * Setter for <code>customer.restricted_country.restriction</code>.
     */
    public void setRestriction(String restriction) {
        this.restriction = restriction;
    }

    /**
     * Getter for <code>customer.restricted_country.connecting_factor</code>.
     */
    public String getConnectingFactor() {
        return this.connectingFactor;
    }

    /**
     * Setter for <code>customer.restricted_country.connecting_factor</code>.
     */
    public void setConnectingFactor(String connectingFactor) {
        this.connectingFactor = connectingFactor;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RestrictedCountry other = (RestrictedCountry) obj;
        if (this.countryCode == null) {
            if (other.countryCode != null)
                return false;
        }
        else if (!this.countryCode.equals(other.countryCode))
            return false;
        if (this.restriction == null) {
            if (other.restriction != null)
                return false;
        }
        else if (!this.restriction.equals(other.restriction))
            return false;
        if (this.connectingFactor == null) {
            if (other.connectingFactor != null)
                return false;
        }
        else if (!this.connectingFactor.equals(other.connectingFactor))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        result = prime * result + ((this.restriction == null) ? 0 : this.restriction.hashCode());
        result = prime * result + ((this.connectingFactor == null) ? 0 : this.connectingFactor.hashCode());
        return result;
    }
}
