/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq;


import org.girardsimon.wealthpay.account.jooq.routines.ManageOutboxPartitions;
import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in account.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>account.manage_outbox_partitions</code>
     */
    public static void manageOutboxPartitions(
          Configuration configuration
        , Integer retentionDays
    ) {
        ManageOutboxPartitions p = new ManageOutboxPartitions();
        p.setRetentionDays(retentionDays);

        p.execute(configuration);
    }
}
