/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq;


import org.girardsimon.wealthpay.account.jooq.routines.DbzPublicationIsCanonical;
import org.girardsimon.wealthpay.account.jooq.routines.ManageOutboxPartitions;
import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in account.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>account.dbz_publication_is_canonical</code>
     */
    public static Boolean dbzPublicationIsCanonical(
          Configuration configuration
    ) {
        DbzPublicationIsCanonical f = new DbzPublicationIsCanonical();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>account.dbz_publication_is_canonical</code> as a field.
     */
    public static Field<Boolean> dbzPublicationIsCanonical() {
        DbzPublicationIsCanonical f = new DbzPublicationIsCanonical();

        return f.asField();
    }

    /**
     * Call <code>account.manage_outbox_partitions</code>
     */
    public static void manageOutboxPartitions(
          Configuration configuration
        , Integer retentionDays
    ) {
        ManageOutboxPartitions p = new ManageOutboxPartitions();
        p.setRetentionDays(retentionDays);

        p.execute(configuration);
    }
}
