/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq;


import org.girardsimon.wealthpay.account.jooq.tables.AccountBalanceView;
import org.girardsimon.wealthpay.account.jooq.tables.EventStore;
import org.girardsimon.wealthpay.account.jooq.tables.FlywaySchemaHistory;
import org.girardsimon.wealthpay.account.jooq.tables.Outbox;
import org.girardsimon.wealthpay.account.jooq.tables.ProcessedReservations;
import org.girardsimon.wealthpay.account.jooq.tables.ProcessedTransactions;


/**
 * Convenience access to all tables in account.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>account.account_balance_view</code>.
     */
    public static final AccountBalanceView ACCOUNT_BALANCE_VIEW = AccountBalanceView.ACCOUNT_BALANCE_VIEW;

    /**
     * The table <code>account.event_store</code>.
     */
    public static final EventStore EVENT_STORE = EventStore.EVENT_STORE;

    /**
     * The table <code>account.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>account.outbox</code>.
     */
    public static final Outbox OUTBOX = Outbox.OUTBOX;

    /**
     * The table <code>account.processed_reservations</code>.
     */
    public static final ProcessedReservations PROCESSED_RESERVATIONS = ProcessedReservations.PROCESSED_RESERVATIONS;

    /**
     * The table <code>account.processed_transactions</code>.
     */
    public static final ProcessedTransactions PROCESSED_TRANSACTIONS = ProcessedTransactions.PROCESSED_TRANSACTIONS;
}
