/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecisionMatch;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionDecisionMatchRecord extends UpdatableRecordImpl<AdmissionDecisionMatchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.admission_decision_match.decision_id</code>.
     */
    public void setDecisionId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.admission_decision_match.decision_id</code>.
     */
    public UUID getDecisionId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>customer.admission_decision_match.ordinal</code>.
     */
    public void setOrdinal(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.admission_decision_match.ordinal</code>.
     */
    public Integer getOrdinal() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>customer.admission_decision_match.restriction</code>.
     */
    public void setRestriction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.admission_decision_match.restriction</code>.
     */
    public String getRestriction() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>customer.admission_decision_match.connecting_factor</code>.
     */
    public void setConnectingFactor(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>customer.admission_decision_match.connecting_factor</code>.
     */
    public String getConnectingFactor() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>customer.admission_decision_match.triggering_country</code>.
     */
    public void setTriggeringCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>customer.admission_decision_match.triggering_country</code>.
     */
    public String getTriggeringCountry() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdmissionDecisionMatchRecord
     */
    public AdmissionDecisionMatchRecord() {
        super(AdmissionDecisionMatch.ADMISSION_DECISION_MATCH);
    }

    /**
     * Create a detached, initialised AdmissionDecisionMatchRecord
     */
    public AdmissionDecisionMatchRecord(UUID decisionId, Integer ordinal, String restriction, String connectingFactor, String triggeringCountry) {
        super(AdmissionDecisionMatch.ADMISSION_DECISION_MATCH);

        setDecisionId(decisionId);
        setOrdinal(ordinal);
        setRestriction(restriction);
        setConnectingFactor(connectingFactor);
        setTriggeringCountry(triggeringCountry);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AdmissionDecisionMatchRecord
     */
    public AdmissionDecisionMatchRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.AdmissionDecisionMatch value) {
        super(AdmissionDecisionMatch.ADMISSION_DECISION_MATCH);

        if (value != null) {
            setDecisionId(value.getDecisionId());
            setOrdinal(value.getOrdinal());
            setRestriction(value.getRestriction());
            setConnectingFactor(value.getConnectingFactor());
            setTriggeringCountry(value.getTriggeringCountry());
            resetChangedOnNotNull();
        }
    }
}
