/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionPolicy;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionPolicyRecord extends UpdatableRecordImpl<AdmissionPolicyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.admission_policy.singleton</code>.
     */
    public void setSingleton(Boolean value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.admission_policy.singleton</code>.
     */
    public Boolean getSingleton() {
        return (Boolean) get(0);
    }

    /**
     * Setter for <code>customer.admission_policy.version</code>.
     */
    public void setVersion(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.admission_policy.version</code>.
     */
    public Long getVersion() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Boolean> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdmissionPolicyRecord
     */
    public AdmissionPolicyRecord() {
        super(AdmissionPolicy.ADMISSION_POLICY);
    }

    /**
     * Create a detached, initialised AdmissionPolicyRecord
     */
    public AdmissionPolicyRecord(Boolean singleton, Long version) {
        super(AdmissionPolicy.ADMISSION_POLICY);

        setSingleton(singleton);
        setVersion(version);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AdmissionPolicyRecord
     */
    public AdmissionPolicyRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.AdmissionPolicy value) {
        super(AdmissionPolicy.ADMISSION_POLICY);

        if (value != null) {
            setSingleton(value.getSingleton());
            setVersion(value.getVersion());
            resetChangedOnNotNull();
        }
    }
}
