/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecision;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionDecisionRecord extends UpdatableRecordImpl<AdmissionDecisionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.admission_decision.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.admission_decision.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>customer.admission_decision.idempotency_key</code>.
     */
    public void setIdempotencyKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.admission_decision.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customer.admission_decision.policy_version</code>.
     */
    public void setPolicyVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.admission_decision.policy_version</code>.
     */
    public Long getPolicyVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>customer.admission_decision.outcome</code>.
     */
    public void setOutcome(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>customer.admission_decision.outcome</code>.
     */
    public String getOutcome() {
        return (String) get(3);
    }

    /**
     * Setter for <code>customer.admission_decision.subject_type</code>.
     */
    public void setSubjectType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>customer.admission_decision.subject_type</code>.
     */
    public String getSubjectType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>customer.admission_decision.nationalities</code>.
     */
    public void setNationalities(String[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>customer.admission_decision.nationalities</code>.
     */
    public String[] getNationalities() {
        return (String[]) get(5);
    }

    /**
     * Setter for <code>customer.admission_decision.country_of_residence</code>.
     */
    public void setCountryOfResidence(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>customer.admission_decision.country_of_residence</code>.
     */
    public String getCountryOfResidence() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>customer.admission_decision.country_of_incorporation</code>.
     */
    public void setCountryOfIncorporation(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>customer.admission_decision.country_of_incorporation</code>.
     */
    public String getCountryOfIncorporation() {
        return (String) get(7);
    }

    /**
     * Setter for <code>customer.admission_decision.decided_at</code>.
     */
    public void setDecidedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>customer.admission_decision.decided_at</code>.
     */
    public OffsetDateTime getDecidedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>customer.admission_decision.recorded_at</code>.
     */
    public void setRecordedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>customer.admission_decision.recorded_at</code>.
     */
    public OffsetDateTime getRecordedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdmissionDecisionRecord
     */
    public AdmissionDecisionRecord() {
        super(AdmissionDecision.ADMISSION_DECISION);
    }

    /**
     * Create a detached, initialised AdmissionDecisionRecord
     */
    public AdmissionDecisionRecord(UUID id, String idempotencyKey, Long policyVersion, String outcome, String subjectType, String[] nationalities, String countryOfResidence, String countryOfIncorporation, OffsetDateTime decidedAt, OffsetDateTime recordedAt) {
        super(AdmissionDecision.ADMISSION_DECISION);

        setId(id);
        setIdempotencyKey(idempotencyKey);
        setPolicyVersion(policyVersion);
        setOutcome(outcome);
        setSubjectType(subjectType);
        setNationalities(nationalities);
        setCountryOfResidence(countryOfResidence);
        setCountryOfIncorporation(countryOfIncorporation);
        setDecidedAt(decidedAt);
        setRecordedAt(recordedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AdmissionDecisionRecord
     */
    public AdmissionDecisionRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.AdmissionDecision value) {
        super(AdmissionDecision.ADMISSION_DECISION);

        if (value != null) {
            setId(value.getId());
            setIdempotencyKey(value.getIdempotencyKey());
            setPolicyVersion(value.getPolicyVersion());
            setOutcome(value.getOutcome());
            setSubjectType(value.getSubjectType());
            setNationalities(value.getNationalities());
            setCountryOfResidence(value.getCountryOfResidence());
            setCountryOfIncorporation(value.getCountryOfIncorporation());
            setDecidedAt(value.getDecidedAt());
            setRecordedAt(value.getRecordedAt());
            resetChangedOnNotNull();
        }
    }
}
