/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.tables.CustomerNationality;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerNationalityRecord extends UpdatableRecordImpl<CustomerNationalityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.customer_nationality.customer_id</code>.
     */
    public void setCustomerId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.customer_nationality.customer_id</code>.
     */
    public UUID getCustomerId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>customer.customer_nationality.kind</code>.
     */
    public void setKind(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.customer_nationality.kind</code>.
     */
    public String getKind() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customer.customer_nationality.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.customer_nationality.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerNationalityRecord
     */
    public CustomerNationalityRecord() {
        super(CustomerNationality.CUSTOMER_NATIONALITY);
    }

    /**
     * Create a detached, initialised CustomerNationalityRecord
     */
    public CustomerNationalityRecord(UUID customerId, String kind, String countryCode) {
        super(CustomerNationality.CUSTOMER_NATIONALITY);

        setCustomerId(customerId);
        setKind(kind);
        setCountryCode(countryCode);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomerNationalityRecord
     */
    public CustomerNationalityRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.CustomerNationality value) {
        super(CustomerNationality.CUSTOMER_NATIONALITY);

        if (value != null) {
            setCustomerId(value.getCustomerId());
            setKind(value.getKind());
            setCountryCode(value.getCountryCode());
            resetChangedOnNotNull();
        }
    }
}
