/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.tables.CustomerStatusTransition;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerStatusTransitionRecord extends UpdatableRecordImpl<CustomerStatusTransitionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.customer_status_transition.customer_id</code>.
     */
    public void setCustomerId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.customer_id</code>.
     */
    public UUID getCustomerId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>customer.customer_status_transition.sequence_no</code>.
     */
    public void setSequenceNo(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.sequence_no</code>.
     */
    public Integer getSequenceNo() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>customer.customer_status_transition.from_status</code>.
     */
    public void setFromStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.from_status</code>.
     */
    public String getFromStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>customer.customer_status_transition.to_status</code>.
     */
    public void setToStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.to_status</code>.
     */
    public String getToStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>customer.customer_status_transition.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>customer.customer_status_transition.recorded_at</code>.
     */
    public void setRecordedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.recorded_at</code>.
     */
    public OffsetDateTime getRecordedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>customer.customer_status_transition.actor</code>.
     */
    public void setActor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.actor</code>.
     */
    public String getActor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>customer.customer_status_transition.reason</code>.
     */
    public void setReason(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>customer.customer_status_transition.reason</code>.
     */
    public String getReason() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerStatusTransitionRecord
     */
    public CustomerStatusTransitionRecord() {
        super(CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION);
    }

    /**
     * Create a detached, initialised CustomerStatusTransitionRecord
     */
    public CustomerStatusTransitionRecord(UUID customerId, Integer sequenceNo, String fromStatus, String toStatus, OffsetDateTime occurredAt, OffsetDateTime recordedAt, String actor, String reason) {
        super(CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION);

        setCustomerId(customerId);
        setSequenceNo(sequenceNo);
        setFromStatus(fromStatus);
        setToStatus(toStatus);
        setOccurredAt(occurredAt);
        setRecordedAt(recordedAt);
        setActor(actor);
        setReason(reason);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomerStatusTransitionRecord
     */
    public CustomerStatusTransitionRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.CustomerStatusTransition value) {
        super(CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION);

        if (value != null) {
            setCustomerId(value.getCustomerId());
            setSequenceNo(value.getSequenceNo());
            setFromStatus(value.getFromStatus());
            setToStatus(value.getToStatus());
            setOccurredAt(value.getOccurredAt());
            setRecordedAt(value.getRecordedAt());
            setActor(value.getActor());
            setReason(value.getReason());
            resetChangedOnNotNull();
        }
    }
}
