/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.tables.Customer;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.customer.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.customer.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>customer.customer.customer_number</code>.
     */
    public void setCustomerNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.customer.customer_number</code>.
     */
    public String getCustomerNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customer.customer.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.customer.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>customer.customer.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>customer.customer.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>customer.customer.registered_at</code>.
     */
    public void setRegisteredAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>customer.customer.registered_at</code>.
     */
    public OffsetDateTime getRegisteredAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>customer.customer.activated_at</code>.
     */
    public void setActivatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>customer.customer.activated_at</code>.
     */
    public OffsetDateTime getActivatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>customer.customer.kind</code>.
     */
    public void setKind(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>customer.customer.kind</code>.
     */
    public String getKind() {
        return (String) get(6);
    }

    /**
     * Setter for <code>customer.customer.given_name</code>.
     */
    public void setGivenName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>customer.customer.given_name</code>.
     */
    public String getGivenName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>customer.customer.middle_name</code>.
     */
    public void setMiddleName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>customer.customer.middle_name</code>.
     */
    public String getMiddleName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>customer.customer.family_name</code>.
     */
    public void setFamilyName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>customer.customer.family_name</code>.
     */
    public String getFamilyName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>customer.customer.date_of_birth</code>.
     */
    public void setDateOfBirth(LocalDate value) {
        set(10, value);
    }

    /**
     * Getter for <code>customer.customer.date_of_birth</code>.
     */
    public LocalDate getDateOfBirth() {
        return (LocalDate) get(10);
    }

    /**
     * Setter for <code>customer.customer.gender</code>.
     */
    public void setGender(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>customer.customer.gender</code>.
     */
    public String getGender() {
        return (String) get(11);
    }

    /**
     * Setter for <code>customer.customer.country_of_residence</code>.
     */
    public void setCountryOfResidence(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>customer.customer.country_of_residence</code>.
     */
    public String getCountryOfResidence() {
        return (String) get(12);
    }

    /**
     * Setter for <code>customer.customer.registered_name</code>.
     */
    public void setRegisteredName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>customer.customer.registered_name</code>.
     */
    public String getRegisteredName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>customer.customer.registration_number</code>.
     */
    public void setRegistrationNumber(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>customer.customer.registration_number</code>.
     */
    public String getRegistrationNumber() {
        return (String) get(14);
    }

    /**
     * Setter for <code>customer.customer.country_of_incorporation</code>.
     */
    public void setCountryOfIncorporation(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>customer.customer.country_of_incorporation</code>.
     */
    public String getCountryOfIncorporation() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER_);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(UUID id, String customerNumber, String email, String status, OffsetDateTime registeredAt, OffsetDateTime activatedAt, String kind, String givenName, String middleName, String familyName, LocalDate dateOfBirth, String gender, String countryOfResidence, String registeredName, String registrationNumber, String countryOfIncorporation) {
        super(Customer.CUSTOMER_);

        setId(id);
        setCustomerNumber(customerNumber);
        setEmail(email);
        setStatus(status);
        setRegisteredAt(registeredAt);
        setActivatedAt(activatedAt);
        setKind(kind);
        setGivenName(givenName);
        setMiddleName(middleName);
        setFamilyName(familyName);
        setDateOfBirth(dateOfBirth);
        setGender(gender);
        setCountryOfResidence(countryOfResidence);
        setRegisteredName(registeredName);
        setRegistrationNumber(registrationNumber);
        setCountryOfIncorporation(countryOfIncorporation);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.Customer value) {
        super(Customer.CUSTOMER_);

        if (value != null) {
            setId(value.getId());
            setCustomerNumber(value.getCustomerNumber());
            setEmail(value.getEmail());
            setStatus(value.getStatus());
            setRegisteredAt(value.getRegisteredAt());
            setActivatedAt(value.getActivatedAt());
            setKind(value.getKind());
            setGivenName(value.getGivenName());
            setMiddleName(value.getMiddleName());
            setFamilyName(value.getFamilyName());
            setDateOfBirth(value.getDateOfBirth());
            setGender(value.getGender());
            setCountryOfResidence(value.getCountryOfResidence());
            setRegisteredName(value.getRegisteredName());
            setRegistrationNumber(value.getRegistrationNumber());
            setCountryOfIncorporation(value.getCountryOfIncorporation());
            resetChangedOnNotNull();
        }
    }
}
