/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.tables.CustomerAdmission;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerAdmissionRecord extends UpdatableRecordImpl<CustomerAdmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.customer_admission.customer_id</code>.
     */
    public void setCustomerId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.customer_admission.customer_id</code>.
     */
    public UUID getCustomerId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>customer.customer_admission.decision_id</code>.
     */
    public void setDecisionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.customer_admission.decision_id</code>.
     */
    public UUID getDecisionId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>customer.customer_admission.outcome</code>.
     */
    public void setOutcome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.customer_admission.outcome</code>.
     */
    public String getOutcome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>customer.customer_admission.subject_type</code>.
     */
    public void setSubjectType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>customer.customer_admission.subject_type</code>.
     */
    public String getSubjectType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>customer.customer_admission.linked_at</code>.
     */
    public void setLinkedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>customer.customer_admission.linked_at</code>.
     */
    public OffsetDateTime getLinkedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerAdmissionRecord
     */
    public CustomerAdmissionRecord() {
        super(CustomerAdmission.CUSTOMER_ADMISSION);
    }

    /**
     * Create a detached, initialised CustomerAdmissionRecord
     */
    public CustomerAdmissionRecord(UUID customerId, UUID decisionId, String outcome, String subjectType, OffsetDateTime linkedAt) {
        super(CustomerAdmission.CUSTOMER_ADMISSION);

        setCustomerId(customerId);
        setDecisionId(decisionId);
        setOutcome(outcome);
        setSubjectType(subjectType);
        setLinkedAt(linkedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomerAdmissionRecord
     */
    public CustomerAdmissionRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.CustomerAdmission value) {
        super(CustomerAdmission.CUSTOMER_ADMISSION);

        if (value != null) {
            setCustomerId(value.getCustomerId());
            setDecisionId(value.getDecisionId());
            setOutcome(value.getOutcome());
            setSubjectType(value.getSubjectType());
            setLinkedAt(value.getLinkedAt());
            resetChangedOnNotNull();
        }
    }
}
