/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import org.girardsimon.wealthpay.customer.jooq.tables.LicensedCountry;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LicensedCountryRecord extends UpdatableRecordImpl<LicensedCountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.licensed_country.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.licensed_country.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>customer.licensed_country.connecting_factor</code>.
     */
    public void setConnectingFactor(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.licensed_country.connecting_factor</code>.
     */
    public String getConnectingFactor() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LicensedCountryRecord
     */
    public LicensedCountryRecord() {
        super(LicensedCountry.LICENSED_COUNTRY);
    }

    /**
     * Create a detached, initialised LicensedCountryRecord
     */
    public LicensedCountryRecord(String countryCode, String connectingFactor) {
        super(LicensedCountry.LICENSED_COUNTRY);

        setCountryCode(countryCode);
        setConnectingFactor(connectingFactor);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LicensedCountryRecord
     */
    public LicensedCountryRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.LicensedCountry value) {
        super(LicensedCountry.LICENSED_COUNTRY);

        if (value != null) {
            setCountryCode(value.getCountryCode());
            setConnectingFactor(value.getConnectingFactor());
            resetChangedOnNotNull();
        }
    }
}
