/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.tables.ProcessedRegistrations;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedRegistrationsRecord extends UpdatableRecordImpl<ProcessedRegistrationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.processed_registrations.idempotency_key</code>.
     */
    public void setIdempotencyKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.processed_registrations.idempotency_key</code>.
     */
    public String getIdempotencyKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>customer.processed_registrations.fingerprint</code>.
     */
    public void setFingerprint(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.processed_registrations.fingerprint</code>.
     */
    public String getFingerprint() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customer.processed_registrations.customer_id</code>.
     */
    public void setCustomerId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.processed_registrations.customer_id</code>.
     */
    public UUID getCustomerId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>customer.processed_registrations.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>customer.processed_registrations.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessedRegistrationsRecord
     */
    public ProcessedRegistrationsRecord() {
        super(ProcessedRegistrations.PROCESSED_REGISTRATIONS);
    }

    /**
     * Create a detached, initialised ProcessedRegistrationsRecord
     */
    public ProcessedRegistrationsRecord(String idempotencyKey, String fingerprint, UUID customerId, OffsetDateTime occurredAt) {
        super(ProcessedRegistrations.PROCESSED_REGISTRATIONS);

        setIdempotencyKey(idempotencyKey);
        setFingerprint(fingerprint);
        setCustomerId(customerId);
        setOccurredAt(occurredAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ProcessedRegistrationsRecord
     */
    public ProcessedRegistrationsRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.ProcessedRegistrations value) {
        super(ProcessedRegistrations.PROCESSED_REGISTRATIONS);

        if (value != null) {
            setIdempotencyKey(value.getIdempotencyKey());
            setFingerprint(value.getFingerprint());
            setCustomerId(value.getCustomerId());
            setOccurredAt(value.getOccurredAt());
            resetChangedOnNotNull();
        }
    }
}
