/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables.records;


import org.girardsimon.wealthpay.customer.jooq.tables.RestrictedCountry;
import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RestrictedCountryRecord extends UpdatableRecordImpl<RestrictedCountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>customer.restricted_country.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>customer.restricted_country.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>customer.restricted_country.restriction</code>.
     */
    public void setRestriction(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customer.restricted_country.restriction</code>.
     */
    public String getRestriction() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customer.restricted_country.connecting_factor</code>.
     */
    public void setConnectingFactor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customer.restricted_country.connecting_factor</code>.
     */
    public String getConnectingFactor() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RestrictedCountryRecord
     */
    public RestrictedCountryRecord() {
        super(RestrictedCountry.RESTRICTED_COUNTRY);
    }

    /**
     * Create a detached, initialised RestrictedCountryRecord
     */
    public RestrictedCountryRecord(String countryCode, String restriction, String connectingFactor) {
        super(RestrictedCountry.RESTRICTED_COUNTRY);

        setCountryCode(countryCode);
        setRestriction(restriction);
        setConnectingFactor(connectingFactor);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RestrictedCountryRecord
     */
    public RestrictedCountryRecord(org.girardsimon.wealthpay.customer.jooq.tables.pojos.RestrictedCountry value) {
        super(RestrictedCountry.RESTRICTED_COUNTRY);

        if (value != null) {
            setCountryCode(value.getCountryCode());
            setRestriction(value.getRestriction());
            setConnectingFactor(value.getConnectingFactor());
            resetChangedOnNotNull();
        }
    }
}
