/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq;


import java.util.Arrays;
import java.util.List;

import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecision;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecisionMatch;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionPolicy;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerAdmission;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerNationality;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerStatusTransition;
import org.girardsimon.wealthpay.customer.jooq.tables.FlywaySchemaHistory;
import org.girardsimon.wealthpay.customer.jooq.tables.LicensedCountry;
import org.girardsimon.wealthpay.customer.jooq.tables.ProcessedRegistrations;
import org.girardsimon.wealthpay.customer.jooq.tables.RestrictedCountry;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Customer extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer</code>
     */
    public static final Customer CUSTOMER = new Customer();

    /**
     * The table <code>customer.admission_decision</code>.
     */
    public final AdmissionDecision ADMISSION_DECISION = AdmissionDecision.ADMISSION_DECISION;

    /**
     * The table <code>customer.admission_decision_match</code>.
     */
    public final AdmissionDecisionMatch ADMISSION_DECISION_MATCH = AdmissionDecisionMatch.ADMISSION_DECISION_MATCH;

    /**
     * The table <code>customer.admission_policy</code>.
     */
    public final AdmissionPolicy ADMISSION_POLICY = AdmissionPolicy.ADMISSION_POLICY;

    /**
     * The table <code>customer.customer</code>.
     */
    public final org.girardsimon.wealthpay.customer.jooq.tables.Customer CUSTOMER_ = org.girardsimon.wealthpay.customer.jooq.tables.Customer.CUSTOMER_;

    /**
     * The table <code>customer.customer_admission</code>.
     */
    public final CustomerAdmission CUSTOMER_ADMISSION = CustomerAdmission.CUSTOMER_ADMISSION;

    /**
     * The table <code>customer.customer_nationality</code>.
     */
    public final CustomerNationality CUSTOMER_NATIONALITY = CustomerNationality.CUSTOMER_NATIONALITY;

    /**
     * The table <code>customer.customer_status_transition</code>.
     */
    public final CustomerStatusTransition CUSTOMER_STATUS_TRANSITION = CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION;

    /**
     * The table <code>customer.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>customer.licensed_country</code>.
     */
    public final LicensedCountry LICENSED_COUNTRY = LicensedCountry.LICENSED_COUNTRY;

    /**
     * The table <code>customer.processed_registrations</code>.
     */
    public final ProcessedRegistrations PROCESSED_REGISTRATIONS = ProcessedRegistrations.PROCESSED_REGISTRATIONS;

    /**
     * The table <code>customer.restricted_country</code>.
     */
    public final RestrictedCountry RESTRICTED_COUNTRY = RestrictedCountry.RESTRICTED_COUNTRY;

    /**
     * No further instances allowed
     */
    private Customer() {
        super("customer", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.CUSTOMER_NUMBER_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AdmissionDecision.ADMISSION_DECISION,
            AdmissionDecisionMatch.ADMISSION_DECISION_MATCH,
            AdmissionPolicy.ADMISSION_POLICY,
            org.girardsimon.wealthpay.customer.jooq.tables.Customer.CUSTOMER_,
            CustomerAdmission.CUSTOMER_ADMISSION,
            CustomerNationality.CUSTOMER_NATIONALITY,
            CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            LicensedCountry.LICENSED_COUNTRY,
            ProcessedRegistrations.PROCESSED_REGISTRATIONS,
            RestrictedCountry.RESTRICTED_COUNTRY
        );
    }
}
