/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq;


import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecision;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecisionMatch;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerNationality;
import org.girardsimon.wealthpay.customer.jooq.tables.FlywaySchemaHistory;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in customer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_ADMISSION_DECISION_DECIDED_AT = Internal.createIndex(DSL.name("idx_admission_decision_decided_at"), AdmissionDecision.ADMISSION_DECISION, new OrderField[] { AdmissionDecision.ADMISSION_DECISION.DECIDED_AT }, false);
    public static final Index IDX_ADMISSION_DECISION_IDEMPOTENCY_KEY = Internal.createIndex(DSL.name("idx_admission_decision_idempotency_key"), AdmissionDecision.ADMISSION_DECISION, new OrderField[] { AdmissionDecision.ADMISSION_DECISION.IDEMPOTENCY_KEY }, false);
    public static final Index IDX_ADMISSION_DECISION_MATCH_PRIMARY_RESTRICTION = Internal.createIndex(DSL.name("idx_admission_decision_match_primary_restriction"), AdmissionDecisionMatch.ADMISSION_DECISION_MATCH, new OrderField[] { AdmissionDecisionMatch.ADMISSION_DECISION_MATCH.RESTRICTION }, false);
    public static final Index IDX_CUSTOMER_NATIONALITY_COUNTRY_CODE = Internal.createIndex(DSL.name("idx_customer_nationality_country_code"), CustomerNationality.CUSTOMER_NATIONALITY, new OrderField[] { CustomerNationality.CUSTOMER_NATIONALITY.COUNTRY_CODE }, false);
}
