/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq;


import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecision;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecisionMatch;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionPolicy;
import org.girardsimon.wealthpay.customer.jooq.tables.Customer;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerAdmission;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerNationality;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerStatusTransition;
import org.girardsimon.wealthpay.customer.jooq.tables.FlywaySchemaHistory;
import org.girardsimon.wealthpay.customer.jooq.tables.LicensedCountry;
import org.girardsimon.wealthpay.customer.jooq.tables.ProcessedRegistrations;
import org.girardsimon.wealthpay.customer.jooq.tables.RestrictedCountry;
import org.girardsimon.wealthpay.customer.jooq.tables.records.AdmissionDecisionMatchRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.AdmissionDecisionRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.AdmissionPolicyRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerAdmissionRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerNationalityRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerStatusTransitionRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.FlywaySchemaHistoryRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.LicensedCountryRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.ProcessedRegistrationsRecord;
import org.girardsimon.wealthpay.customer.jooq.tables.records.RestrictedCountryRecord;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * customer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdmissionDecisionRecord> PK_ADMISSION_DECISION = Internal.createUniqueKey(AdmissionDecision.ADMISSION_DECISION, DSL.name("pk_admission_decision"), new TableField[] { AdmissionDecision.ADMISSION_DECISION.ID }, true);
    public static final UniqueKey<AdmissionDecisionRecord> UQ_ADMISSION_DECISION_OUTCOME_SUBJECT = Internal.createUniqueKey(AdmissionDecision.ADMISSION_DECISION, DSL.name("uq_admission_decision_outcome_subject"), new TableField[] { AdmissionDecision.ADMISSION_DECISION.ID, AdmissionDecision.ADMISSION_DECISION.OUTCOME, AdmissionDecision.ADMISSION_DECISION.SUBJECT_TYPE }, true);
    public static final UniqueKey<AdmissionDecisionMatchRecord> PK_ADMISSION_DECISION_MATCH = Internal.createUniqueKey(AdmissionDecisionMatch.ADMISSION_DECISION_MATCH, DSL.name("pk_admission_decision_match"), new TableField[] { AdmissionDecisionMatch.ADMISSION_DECISION_MATCH.DECISION_ID, AdmissionDecisionMatch.ADMISSION_DECISION_MATCH.ORDINAL }, true);
    public static final UniqueKey<AdmissionPolicyRecord> PK_ADMISSION_POLICY = Internal.createUniqueKey(AdmissionPolicy.ADMISSION_POLICY, DSL.name("pk_admission_policy"), new TableField[] { AdmissionPolicy.ADMISSION_POLICY.SINGLETON }, true);
    public static final UniqueKey<CustomerRecord> PK_CUSTOMER = Internal.createUniqueKey(Customer.CUSTOMER_, DSL.name("pk_customer"), new TableField[] { Customer.CUSTOMER_.ID }, true);
    public static final UniqueKey<CustomerRecord> UQ_CUSTOMER_EMAIL = Internal.createUniqueKey(Customer.CUSTOMER_, DSL.name("uq_customer_email"), new TableField[] { Customer.CUSTOMER_.EMAIL }, true);
    public static final UniqueKey<CustomerRecord> UQ_CUSTOMER_ID_KIND = Internal.createUniqueKey(Customer.CUSTOMER_, DSL.name("uq_customer_id_kind"), new TableField[] { Customer.CUSTOMER_.ID, Customer.CUSTOMER_.KIND }, true);
    public static final UniqueKey<CustomerRecord> UQ_CUSTOMER_NUMBER = Internal.createUniqueKey(Customer.CUSTOMER_, DSL.name("uq_customer_number"), new TableField[] { Customer.CUSTOMER_.CUSTOMER_NUMBER }, true);
    public static final UniqueKey<CustomerAdmissionRecord> PK_CUSTOMER_ADMISSION = Internal.createUniqueKey(CustomerAdmission.CUSTOMER_ADMISSION, DSL.name("pk_customer_admission"), new TableField[] { CustomerAdmission.CUSTOMER_ADMISSION.CUSTOMER_ID, CustomerAdmission.CUSTOMER_ADMISSION.DECISION_ID }, true);
    public static final UniqueKey<CustomerAdmissionRecord> UQ_CUSTOMER_ADMISSION_DECISION = Internal.createUniqueKey(CustomerAdmission.CUSTOMER_ADMISSION, DSL.name("uq_customer_admission_decision"), new TableField[] { CustomerAdmission.CUSTOMER_ADMISSION.DECISION_ID }, true);
    public static final UniqueKey<CustomerNationalityRecord> PK_CUSTOMER_NATIONALITY = Internal.createUniqueKey(CustomerNationality.CUSTOMER_NATIONALITY, DSL.name("pk_customer_nationality"), new TableField[] { CustomerNationality.CUSTOMER_NATIONALITY.CUSTOMER_ID, CustomerNationality.CUSTOMER_NATIONALITY.COUNTRY_CODE }, true);
    public static final UniqueKey<CustomerStatusTransitionRecord> PK_CUSTOMER_STATUS_TRANSITION = Internal.createUniqueKey(CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION, DSL.name("pk_customer_status_transition"), new TableField[] { CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION.CUSTOMER_ID, CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION.SEQUENCE_NO }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<LicensedCountryRecord> PK_LICENSED_COUNTRY = Internal.createUniqueKey(LicensedCountry.LICENSED_COUNTRY, DSL.name("pk_licensed_country"), new TableField[] { LicensedCountry.LICENSED_COUNTRY.COUNTRY_CODE, LicensedCountry.LICENSED_COUNTRY.CONNECTING_FACTOR }, true);
    public static final UniqueKey<ProcessedRegistrationsRecord> PK_PROCESSED_REGISTRATIONS = Internal.createUniqueKey(ProcessedRegistrations.PROCESSED_REGISTRATIONS, DSL.name("pk_processed_registrations"), new TableField[] { ProcessedRegistrations.PROCESSED_REGISTRATIONS.IDEMPOTENCY_KEY }, true);
    public static final UniqueKey<RestrictedCountryRecord> PK_RESTRICTED_COUNTRY = Internal.createUniqueKey(RestrictedCountry.RESTRICTED_COUNTRY, DSL.name("pk_restricted_country"), new TableField[] { RestrictedCountry.RESTRICTED_COUNTRY.COUNTRY_CODE, RestrictedCountry.RESTRICTED_COUNTRY.RESTRICTION, RestrictedCountry.RESTRICTED_COUNTRY.CONNECTING_FACTOR }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AdmissionDecisionMatchRecord, AdmissionDecisionRecord> ADMISSION_DECISION_MATCH__FK_ADMISSION_DECISION_MATCH_DECISION = Internal.createForeignKey(AdmissionDecisionMatch.ADMISSION_DECISION_MATCH, DSL.name("fk_admission_decision_match_decision"), new TableField[] { AdmissionDecisionMatch.ADMISSION_DECISION_MATCH.DECISION_ID }, Keys.PK_ADMISSION_DECISION, new TableField[] { AdmissionDecision.ADMISSION_DECISION.ID }, true);
    public static final ForeignKey<CustomerAdmissionRecord, CustomerRecord> CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_CUSTOMER = Internal.createForeignKey(CustomerAdmission.CUSTOMER_ADMISSION, DSL.name("fk_customer_admission_customer"), new TableField[] { CustomerAdmission.CUSTOMER_ADMISSION.CUSTOMER_ID, CustomerAdmission.CUSTOMER_ADMISSION.SUBJECT_TYPE }, Keys.UQ_CUSTOMER_ID_KIND, new TableField[] { Customer.CUSTOMER_.ID, Customer.CUSTOMER_.KIND }, true);
    public static final ForeignKey<CustomerAdmissionRecord, AdmissionDecisionRecord> CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_DECISION = Internal.createForeignKey(CustomerAdmission.CUSTOMER_ADMISSION, DSL.name("fk_customer_admission_decision"), new TableField[] { CustomerAdmission.CUSTOMER_ADMISSION.DECISION_ID, CustomerAdmission.CUSTOMER_ADMISSION.OUTCOME, CustomerAdmission.CUSTOMER_ADMISSION.SUBJECT_TYPE }, Keys.UQ_ADMISSION_DECISION_OUTCOME_SUBJECT, new TableField[] { AdmissionDecision.ADMISSION_DECISION.ID, AdmissionDecision.ADMISSION_DECISION.OUTCOME, AdmissionDecision.ADMISSION_DECISION.SUBJECT_TYPE }, true);
    public static final ForeignKey<CustomerNationalityRecord, CustomerRecord> CUSTOMER_NATIONALITY__FK_CUSTOMER_NATIONALITY_CUSTOMER = Internal.createForeignKey(CustomerNationality.CUSTOMER_NATIONALITY, DSL.name("fk_customer_nationality_customer"), new TableField[] { CustomerNationality.CUSTOMER_NATIONALITY.CUSTOMER_ID, CustomerNationality.CUSTOMER_NATIONALITY.KIND }, Keys.UQ_CUSTOMER_ID_KIND, new TableField[] { Customer.CUSTOMER_.ID, Customer.CUSTOMER_.KIND }, true);
    public static final ForeignKey<CustomerStatusTransitionRecord, CustomerRecord> CUSTOMER_STATUS_TRANSITION__FK_CUSTOMER_STATUS_TRANSITION_CUSTOMER = Internal.createForeignKey(CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION, DSL.name("fk_customer_status_transition_customer"), new TableField[] { CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION.CUSTOMER_ID }, Keys.PK_CUSTOMER, new TableField[] { Customer.CUSTOMER_.ID }, true);
}
