/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in customer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>customer.customer_number_seq</code>
     */
    public static final Sequence<Long> CUSTOMER_NUMBER_SEQ = Internal.createSequence("customer_number_seq", Customer.CUSTOMER, SQLDataType.BIGINT.nullable(false), null, null, null, 999999999, false, null);
}
