/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq;


import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecision;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecisionMatch;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionPolicy;
import org.girardsimon.wealthpay.customer.jooq.tables.Customer;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerAdmission;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerNationality;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerStatusTransition;
import org.girardsimon.wealthpay.customer.jooq.tables.FlywaySchemaHistory;
import org.girardsimon.wealthpay.customer.jooq.tables.LicensedCountry;
import org.girardsimon.wealthpay.customer.jooq.tables.ProcessedRegistrations;
import org.girardsimon.wealthpay.customer.jooq.tables.RestrictedCountry;


/**
 * Convenience access to all tables in customer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>customer.admission_decision</code>.
     */
    public static final AdmissionDecision ADMISSION_DECISION = AdmissionDecision.ADMISSION_DECISION;

    /**
     * The table <code>customer.admission_decision_match</code>.
     */
    public static final AdmissionDecisionMatch ADMISSION_DECISION_MATCH = AdmissionDecisionMatch.ADMISSION_DECISION_MATCH;

    /**
     * The table <code>customer.admission_policy</code>.
     */
    public static final AdmissionPolicy ADMISSION_POLICY = AdmissionPolicy.ADMISSION_POLICY;

    /**
     * The table <code>customer.customer</code>.
     */
    public static final Customer CUSTOMER_ = Customer.CUSTOMER_;

    /**
     * The table <code>customer.customer_admission</code>.
     */
    public static final CustomerAdmission CUSTOMER_ADMISSION = CustomerAdmission.CUSTOMER_ADMISSION;

    /**
     * The table <code>customer.customer_nationality</code>.
     */
    public static final CustomerNationality CUSTOMER_NATIONALITY = CustomerNationality.CUSTOMER_NATIONALITY;

    /**
     * The table <code>customer.customer_status_transition</code>.
     */
    public static final CustomerStatusTransition CUSTOMER_STATUS_TRANSITION = CustomerStatusTransition.CUSTOMER_STATUS_TRANSITION;

    /**
     * The table <code>customer.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>customer.licensed_country</code>.
     */
    public static final LicensedCountry LICENSED_COUNTRY = LicensedCountry.LICENSED_COUNTRY;

    /**
     * The table <code>customer.processed_registrations</code>.
     */
    public static final ProcessedRegistrations PROCESSED_REGISTRATIONS = ProcessedRegistrations.PROCESSED_REGISTRATIONS;

    /**
     * The table <code>customer.restricted_country</code>.
     */
    public static final RestrictedCountry RESTRICTED_COUNTRY = RestrictedCountry.RESTRICTED_COUNTRY;
}
