/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables;


import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.Account;
import org.girardsimon.wealthpay.account.jooq.Keys;
import org.girardsimon.wealthpay.account.jooq.tables.records.AccountBalanceViewRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountBalanceView extends TableImpl<AccountBalanceViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>account.account_balance_view</code>
     */
    public static final AccountBalanceView ACCOUNT_BALANCE_VIEW = new AccountBalanceView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountBalanceViewRecord> getRecordType() {
        return AccountBalanceViewRecord.class;
    }

    /**
     * The column <code>account.account_balance_view.account_id</code>.
     */
    public final TableField<AccountBalanceViewRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.account_balance_view.currency</code>.
     */
    public final TableField<AccountBalanceViewRecord, String> CURRENCY = createField(DSL.name("currency"), SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>account.account_balance_view.balance</code>.
     */
    public final TableField<AccountBalanceViewRecord, BigDecimal> BALANCE = createField(DSL.name("balance"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>account.account_balance_view.reserved</code>.
     */
    public final TableField<AccountBalanceViewRecord, BigDecimal> RESERVED = createField(DSL.name("reserved"), SQLDataType.NUMERIC(19, 4).nullable(false), this, "");

    /**
     * The column <code>account.account_balance_view.status</code>.
     */
    public final TableField<AccountBalanceViewRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>account.account_balance_view.version</code>.
     */
    public final TableField<AccountBalanceViewRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>account.account_balance_view.last_updated_at</code>.
     */
    public final TableField<AccountBalanceViewRecord, OffsetDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AccountBalanceView(Name alias, Table<AccountBalanceViewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccountBalanceView(Name alias, Table<AccountBalanceViewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>account.account_balance_view</code> table
     * reference
     */
    public AccountBalanceView(String alias) {
        this(DSL.name(alias), ACCOUNT_BALANCE_VIEW);
    }

    /**
     * Create an aliased <code>account.account_balance_view</code> table
     * reference
     */
    public AccountBalanceView(Name alias) {
        this(alias, ACCOUNT_BALANCE_VIEW);
    }

    /**
     * Create a <code>account.account_balance_view</code> table reference
     */
    public AccountBalanceView() {
        this(DSL.name("account_balance_view"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Account.ACCOUNT;
    }

    @Override
    public UniqueKey<AccountBalanceViewRecord> getPrimaryKey() {
        return Keys.ACCOUNT_BALANCE_VIEW_PKEY;
    }

    @Override
    public AccountBalanceView as(String alias) {
        return new AccountBalanceView(DSL.name(alias), this);
    }

    @Override
    public AccountBalanceView as(Name alias) {
        return new AccountBalanceView(alias, this);
    }

    @Override
    public AccountBalanceView as(Table<?> alias) {
        return new AccountBalanceView(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountBalanceView rename(String name) {
        return new AccountBalanceView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountBalanceView rename(Name name) {
        return new AccountBalanceView(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountBalanceView rename(Table<?> name) {
        return new AccountBalanceView(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountBalanceView where(Condition condition) {
        return new AccountBalanceView(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountBalanceView where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountBalanceView where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountBalanceView where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountBalanceView where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountBalanceView where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountBalanceView where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountBalanceView where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountBalanceView whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountBalanceView whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
