/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.Account;
import org.girardsimon.wealthpay.account.jooq.Keys;
import org.girardsimon.wealthpay.account.jooq.tables.records.AccountSnapshotRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountSnapshot extends TableImpl<AccountSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>account.account_snapshot</code>
     */
    public static final AccountSnapshot ACCOUNT_SNAPSHOT = new AccountSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountSnapshotRecord> getRecordType() {
        return AccountSnapshotRecord.class;
    }

    /**
     * The column <code>account.account_snapshot.account_id</code>.
     */
    public final TableField<AccountSnapshotRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.account_snapshot.state</code>.
     */
    public final TableField<AccountSnapshotRecord, JSONB> STATE = createField(DSL.name("state"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>account.account_snapshot.version</code>.
     */
    public final TableField<AccountSnapshotRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>account.account_snapshot.last_updated_at</code>.
     */
    public final TableField<AccountSnapshotRecord, OffsetDateTime> LAST_UPDATED_AT = createField(DSL.name("last_updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>account.account_snapshot.schema_version</code>.
     */
    public final TableField<AccountSnapshotRecord, Long> SCHEMA_VERSION = createField(DSL.name("schema_version"), SQLDataType.BIGINT.nullable(false), this, "");

    private AccountSnapshot(Name alias, Table<AccountSnapshotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccountSnapshot(Name alias, Table<AccountSnapshotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>account.account_snapshot</code> table reference
     */
    public AccountSnapshot(String alias) {
        this(DSL.name(alias), ACCOUNT_SNAPSHOT);
    }

    /**
     * Create an aliased <code>account.account_snapshot</code> table reference
     */
    public AccountSnapshot(Name alias) {
        this(alias, ACCOUNT_SNAPSHOT);
    }

    /**
     * Create a <code>account.account_snapshot</code> table reference
     */
    public AccountSnapshot() {
        this(DSL.name("account_snapshot"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Account.ACCOUNT;
    }

    @Override
    public UniqueKey<AccountSnapshotRecord> getPrimaryKey() {
        return Keys.ACCOUNT_SNAPSHOT_PKEY;
    }

    @Override
    public AccountSnapshot as(String alias) {
        return new AccountSnapshot(DSL.name(alias), this);
    }

    @Override
    public AccountSnapshot as(Name alias) {
        return new AccountSnapshot(alias, this);
    }

    @Override
    public AccountSnapshot as(Table<?> alias) {
        return new AccountSnapshot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountSnapshot rename(String name) {
        return new AccountSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountSnapshot rename(Name name) {
        return new AccountSnapshot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountSnapshot rename(Table<?> name) {
        return new AccountSnapshot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountSnapshot where(Condition condition) {
        return new AccountSnapshot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountSnapshot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountSnapshot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountSnapshot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountSnapshot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountSnapshot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountSnapshot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountSnapshot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountSnapshot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountSnapshot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
