/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.girardsimon.wealthpay.account.jooq.Account;
import org.girardsimon.wealthpay.account.jooq.Indexes;
import org.girardsimon.wealthpay.account.jooq.tables.records.OutboxCleanupLogRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutboxCleanupLog extends TableImpl<OutboxCleanupLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>account.outbox_cleanup_log</code>
     */
    public static final OutboxCleanupLog OUTBOX_CLEANUP_LOG = new OutboxCleanupLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OutboxCleanupLogRecord> getRecordType() {
        return OutboxCleanupLogRecord.class;
    }

    /**
     * The column <code>account.outbox_cleanup_log.run_at</code>.
     */
    public final TableField<OutboxCleanupLogRecord, OffsetDateTime> RUN_AT = createField(DSL.name("run_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>account.outbox_cleanup_log.partitions_created</code>.
     */
    public final TableField<OutboxCleanupLogRecord, Integer> PARTITIONS_CREATED = createField(DSL.name("partitions_created"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>account.outbox_cleanup_log.partitions_dropped</code>.
     */
    public final TableField<OutboxCleanupLogRecord, Integer> PARTITIONS_DROPPED = createField(DSL.name("partitions_dropped"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>account.outbox_cleanup_log.remaining_partitions</code>.
     */
    public final TableField<OutboxCleanupLogRecord, Integer> REMAINING_PARTITIONS = createField(DSL.name("remaining_partitions"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>account.outbox_cleanup_log.status</code>.
     */
    public final TableField<OutboxCleanupLogRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'success'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>account.outbox_cleanup_log.started_at</code>.
     */
    public final TableField<OutboxCleanupLogRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>account.outbox_cleanup_log.completed_at</code>.
     */
    public final TableField<OutboxCleanupLogRecord, OffsetDateTime> COMPLETED_AT = createField(DSL.name("completed_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>account.outbox_cleanup_log.error_message</code>.
     */
    public final TableField<OutboxCleanupLogRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "");

    private OutboxCleanupLog(Name alias, Table<OutboxCleanupLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OutboxCleanupLog(Name alias, Table<OutboxCleanupLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>account.outbox_cleanup_log</code> table reference
     */
    public OutboxCleanupLog(String alias) {
        this(DSL.name(alias), OUTBOX_CLEANUP_LOG);
    }

    /**
     * Create an aliased <code>account.outbox_cleanup_log</code> table reference
     */
    public OutboxCleanupLog(Name alias) {
        this(alias, OUTBOX_CLEANUP_LOG);
    }

    /**
     * Create a <code>account.outbox_cleanup_log</code> table reference
     */
    public OutboxCleanupLog() {
        this(DSL.name("outbox_cleanup_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Account.ACCOUNT;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OUTBOX_CLEANUP_LOG_COMPLETED_AT_SUCCESS, Indexes.IDX_OUTBOX_CLEANUP_LOG_RUN_AT_DESC);
    }

    @Override
    public List<Check<OutboxCleanupLogRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("outbox_cleanup_log_status_check"), "((status = ANY (ARRAY['success'::text, 'failure'::text])))", true)
        );
    }

    @Override
    public OutboxCleanupLog as(String alias) {
        return new OutboxCleanupLog(DSL.name(alias), this);
    }

    @Override
    public OutboxCleanupLog as(Name alias) {
        return new OutboxCleanupLog(alias, this);
    }

    @Override
    public OutboxCleanupLog as(Table<?> alias) {
        return new OutboxCleanupLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OutboxCleanupLog rename(String name) {
        return new OutboxCleanupLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OutboxCleanupLog rename(Name name) {
        return new OutboxCleanupLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OutboxCleanupLog rename(Table<?> name) {
        return new OutboxCleanupLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxCleanupLog where(Condition condition) {
        return new OutboxCleanupLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxCleanupLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxCleanupLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxCleanupLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxCleanupLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxCleanupLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxCleanupLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxCleanupLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxCleanupLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxCleanupLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
