/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.Account;
import org.girardsimon.wealthpay.account.jooq.Indexes;
import org.girardsimon.wealthpay.account.jooq.Keys;
import org.girardsimon.wealthpay.account.jooq.tables.records.ProcessedReservationsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedReservations extends TableImpl<ProcessedReservationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>account.processed_reservations</code>
     */
    public static final ProcessedReservations PROCESSED_RESERVATIONS = new ProcessedReservations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessedReservationsRecord> getRecordType() {
        return ProcessedReservationsRecord.class;
    }

    /**
     * The column <code>account.processed_reservations.account_id</code>.
     */
    public final TableField<ProcessedReservationsRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.processed_reservations.transaction_id</code>.
     */
    public final TableField<ProcessedReservationsRecord, UUID> TRANSACTION_ID = createField(DSL.name("transaction_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.processed_reservations.reservation_id</code>.
     */
    public final TableField<ProcessedReservationsRecord, UUID> RESERVATION_ID = createField(DSL.name("reservation_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.processed_reservations.phase</code>.
     */
    public final TableField<ProcessedReservationsRecord, String> PHASE = createField(DSL.name("phase"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>account.processed_reservations.occurred_at</code>.
     */
    public final TableField<ProcessedReservationsRecord, OffsetDateTime> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private ProcessedReservations(Name alias, Table<ProcessedReservationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcessedReservations(Name alias, Table<ProcessedReservationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>account.processed_reservations</code> table
     * reference
     */
    public ProcessedReservations(String alias) {
        this(DSL.name(alias), PROCESSED_RESERVATIONS);
    }

    /**
     * Create an aliased <code>account.processed_reservations</code> table
     * reference
     */
    public ProcessedReservations(Name alias) {
        this(alias, PROCESSED_RESERVATIONS);
    }

    /**
     * Create a <code>account.processed_reservations</code> table reference
     */
    public ProcessedReservations() {
        this(DSL.name("processed_reservations"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Account.ACCOUNT;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PROCESSED_RESERVATIONS_OCCURRED_AT_IDX);
    }

    @Override
    public UniqueKey<ProcessedReservationsRecord> getPrimaryKey() {
        return Keys.PROCESSED_RESERVATIONS_PKEY;
    }

    @Override
    public List<UniqueKey<ProcessedReservationsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PROCESSED_RESERVATIONS_ACCOUNT_ID_TRANSACTION_ID_KEY);
    }

    @Override
    public ProcessedReservations as(String alias) {
        return new ProcessedReservations(DSL.name(alias), this);
    }

    @Override
    public ProcessedReservations as(Name alias) {
        return new ProcessedReservations(alias, this);
    }

    @Override
    public ProcessedReservations as(Table<?> alias) {
        return new ProcessedReservations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedReservations rename(String name) {
        return new ProcessedReservations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedReservations rename(Name name) {
        return new ProcessedReservations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedReservations rename(Table<?> name) {
        return new ProcessedReservations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedReservations where(Condition condition) {
        return new ProcessedReservations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedReservations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedReservations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedReservations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedReservations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedReservations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedReservations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedReservations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedReservations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedReservations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
