/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Collection;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.Account;
import org.girardsimon.wealthpay.account.jooq.Keys;
import org.girardsimon.wealthpay.account.jooq.tables.records.ProcessedTransactionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedTransactions extends TableImpl<ProcessedTransactionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>account.processed_transactions</code>
     */
    public static final ProcessedTransactions PROCESSED_TRANSACTIONS = new ProcessedTransactions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessedTransactionsRecord> getRecordType() {
        return ProcessedTransactionsRecord.class;
    }

    /**
     * The column <code>account.processed_transactions.account_id</code>.
     */
    public final TableField<ProcessedTransactionsRecord, UUID> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.processed_transactions.transaction_id</code>.
     */
    public final TableField<ProcessedTransactionsRecord, UUID> TRANSACTION_ID = createField(DSL.name("transaction_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.processed_transactions.occurred_at</code>.
     */
    public final TableField<ProcessedTransactionsRecord, OffsetDateTime> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>account.processed_transactions.fingerprint</code>.
     */
    public final TableField<ProcessedTransactionsRecord, String> FINGERPRINT = createField(DSL.name("fingerprint"), SQLDataType.CHAR(64), this, "");

    private ProcessedTransactions(Name alias, Table<ProcessedTransactionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcessedTransactions(Name alias, Table<ProcessedTransactionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>account.processed_transactions</code> table
     * reference
     */
    public ProcessedTransactions(String alias) {
        this(DSL.name(alias), PROCESSED_TRANSACTIONS);
    }

    /**
     * Create an aliased <code>account.processed_transactions</code> table
     * reference
     */
    public ProcessedTransactions(Name alias) {
        this(alias, PROCESSED_TRANSACTIONS);
    }

    /**
     * Create a <code>account.processed_transactions</code> table reference
     */
    public ProcessedTransactions() {
        this(DSL.name("processed_transactions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Account.ACCOUNT;
    }

    @Override
    public UniqueKey<ProcessedTransactionsRecord> getPrimaryKey() {
        return Keys.PROCESSED_TRANSACTIONS_PKEY;
    }

    @Override
    public ProcessedTransactions as(String alias) {
        return new ProcessedTransactions(DSL.name(alias), this);
    }

    @Override
    public ProcessedTransactions as(Name alias) {
        return new ProcessedTransactions(alias, this);
    }

    @Override
    public ProcessedTransactions as(Table<?> alias) {
        return new ProcessedTransactions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedTransactions rename(String name) {
        return new ProcessedTransactions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedTransactions rename(Name name) {
        return new ProcessedTransactions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedTransactions rename(Table<?> name) {
        return new ProcessedTransactions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedTransactions where(Condition condition) {
        return new ProcessedTransactions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedTransactions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedTransactions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedTransactions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedTransactions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedTransactions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedTransactions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedTransactions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedTransactions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedTransactions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
