/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.records.AdmissionPolicyRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionPolicy extends TableImpl<AdmissionPolicyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.admission_policy</code>
     */
    public static final AdmissionPolicy ADMISSION_POLICY = new AdmissionPolicy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdmissionPolicyRecord> getRecordType() {
        return AdmissionPolicyRecord.class;
    }

    /**
     * The column <code>customer.admission_policy.singleton</code>.
     */
    public final TableField<AdmissionPolicyRecord, Boolean> SINGLETON = createField(DSL.name("singleton"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>customer.admission_policy.version</code>.
     */
    public final TableField<AdmissionPolicyRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    private AdmissionPolicy(Name alias, Table<AdmissionPolicyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AdmissionPolicy(Name alias, Table<AdmissionPolicyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.admission_policy</code> table reference
     */
    public AdmissionPolicy(String alias) {
        this(DSL.name(alias), ADMISSION_POLICY);
    }

    /**
     * Create an aliased <code>customer.admission_policy</code> table reference
     */
    public AdmissionPolicy(Name alias) {
        this(alias, ADMISSION_POLICY);
    }

    /**
     * Create a <code>customer.admission_policy</code> table reference
     */
    public AdmissionPolicy() {
        this(DSL.name("admission_policy"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public UniqueKey<AdmissionPolicyRecord> getPrimaryKey() {
        return Keys.PK_ADMISSION_POLICY;
    }

    @Override
    public List<Check<AdmissionPolicyRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_admission_policy_single_row"), "(singleton)", true),
            Internal.createCheck(this, DSL.name("ck_admission_policy_version_positive"), "((version > 0))", true)
        );
    }

    @Override
    public AdmissionPolicy as(String alias) {
        return new AdmissionPolicy(DSL.name(alias), this);
    }

    @Override
    public AdmissionPolicy as(Name alias) {
        return new AdmissionPolicy(alias, this);
    }

    @Override
    public AdmissionPolicy as(Table<?> alias) {
        return new AdmissionPolicy(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionPolicy rename(String name) {
        return new AdmissionPolicy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionPolicy rename(Name name) {
        return new AdmissionPolicy(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionPolicy rename(Table<?> name) {
        return new AdmissionPolicy(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionPolicy where(Condition condition) {
        return new AdmissionPolicy(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionPolicy where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionPolicy where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionPolicy where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionPolicy where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionPolicy where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionPolicy where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionPolicy where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionPolicy whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionPolicy whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
