/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Indexes;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecision.AdmissionDecisionPath;
import org.girardsimon.wealthpay.customer.jooq.tables.records.AdmissionDecisionMatchRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionDecisionMatch extends TableImpl<AdmissionDecisionMatchRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.admission_decision_match</code>
     */
    public static final AdmissionDecisionMatch ADMISSION_DECISION_MATCH = new AdmissionDecisionMatch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdmissionDecisionMatchRecord> getRecordType() {
        return AdmissionDecisionMatchRecord.class;
    }

    /**
     * The column <code>customer.admission_decision_match.decision_id</code>.
     */
    public final TableField<AdmissionDecisionMatchRecord, UUID> DECISION_ID = createField(DSL.name("decision_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision_match.ordinal</code>.
     */
    public final TableField<AdmissionDecisionMatchRecord, Integer> ORDINAL = createField(DSL.name("ordinal"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision_match.restriction</code>.
     */
    public final TableField<AdmissionDecisionMatchRecord, String> RESTRICTION = createField(DSL.name("restriction"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column
     * <code>customer.admission_decision_match.connecting_factor</code>.
     */
    public final TableField<AdmissionDecisionMatchRecord, String> CONNECTING_FACTOR = createField(DSL.name("connecting_factor"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column
     * <code>customer.admission_decision_match.triggering_country</code>.
     */
    public final TableField<AdmissionDecisionMatchRecord, String> TRIGGERING_COUNTRY = createField(DSL.name("triggering_country"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    private AdmissionDecisionMatch(Name alias, Table<AdmissionDecisionMatchRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AdmissionDecisionMatch(Name alias, Table<AdmissionDecisionMatchRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.admission_decision_match</code> table
     * reference
     */
    public AdmissionDecisionMatch(String alias) {
        this(DSL.name(alias), ADMISSION_DECISION_MATCH);
    }

    /**
     * Create an aliased <code>customer.admission_decision_match</code> table
     * reference
     */
    public AdmissionDecisionMatch(Name alias) {
        this(alias, ADMISSION_DECISION_MATCH);
    }

    /**
     * Create a <code>customer.admission_decision_match</code> table reference
     */
    public AdmissionDecisionMatch() {
        this(DSL.name("admission_decision_match"), null);
    }

    public <O extends Record> AdmissionDecisionMatch(Table<O> path, ForeignKey<O, AdmissionDecisionMatchRecord> childPath, InverseForeignKey<O, AdmissionDecisionMatchRecord> parentPath) {
        super(path, childPath, parentPath, ADMISSION_DECISION_MATCH);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AdmissionDecisionMatchPath extends AdmissionDecisionMatch implements Path<AdmissionDecisionMatchRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AdmissionDecisionMatchPath(Table<O> path, ForeignKey<O, AdmissionDecisionMatchRecord> childPath, InverseForeignKey<O, AdmissionDecisionMatchRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AdmissionDecisionMatchPath(Name alias, Table<AdmissionDecisionMatchRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AdmissionDecisionMatchPath as(String alias) {
            return new AdmissionDecisionMatchPath(DSL.name(alias), this);
        }

        @Override
        public AdmissionDecisionMatchPath as(Name alias) {
            return new AdmissionDecisionMatchPath(alias, this);
        }

        @Override
        public AdmissionDecisionMatchPath as(Table<?> alias) {
            return new AdmissionDecisionMatchPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ADMISSION_DECISION_MATCH_PRIMARY_RESTRICTION);
    }

    @Override
    public UniqueKey<AdmissionDecisionMatchRecord> getPrimaryKey() {
        return Keys.PK_ADMISSION_DECISION_MATCH;
    }

    @Override
    public List<ForeignKey<AdmissionDecisionMatchRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ADMISSION_DECISION_MATCH__FK_ADMISSION_DECISION_MATCH_DECISION);
    }

    private transient AdmissionDecisionPath _admissionDecision;

    /**
     * Get the implicit join path to the
     * <code>customer.admission_decision</code> table.
     */
    public AdmissionDecisionPath admissionDecision() {
        if (_admissionDecision == null)
            _admissionDecision = new AdmissionDecisionPath(this, Keys.ADMISSION_DECISION_MATCH__FK_ADMISSION_DECISION_MATCH_DECISION, null);

        return _admissionDecision;
    }

    @Override
    public List<Check<AdmissionDecisionMatchRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_admission_decision_match_country_shape"), "(((triggering_country)::text ~ '^[A-Z]{2}$'::text))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_match_factor_known"), "(((connecting_factor)::text = ANY ((ARRAY['NATIONALITY'::character varying, 'RESIDENCE'::character varying, 'INCORPORATION'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_match_ordinal_non_negative"), "((ordinal >= 0))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_match_restriction_known"), "(((restriction)::text = ANY ((ARRAY['SANCTIONED'::character varying, 'RESTRICTED_PERSON'::character varying, 'UNLICENSED'::character varying])::text[])))", true)
        );
    }

    @Override
    public AdmissionDecisionMatch as(String alias) {
        return new AdmissionDecisionMatch(DSL.name(alias), this);
    }

    @Override
    public AdmissionDecisionMatch as(Name alias) {
        return new AdmissionDecisionMatch(alias, this);
    }

    @Override
    public AdmissionDecisionMatch as(Table<?> alias) {
        return new AdmissionDecisionMatch(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionDecisionMatch rename(String name) {
        return new AdmissionDecisionMatch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionDecisionMatch rename(Name name) {
        return new AdmissionDecisionMatch(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionDecisionMatch rename(Table<?> name) {
        return new AdmissionDecisionMatch(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecisionMatch where(Condition condition) {
        return new AdmissionDecisionMatch(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecisionMatch where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecisionMatch where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecisionMatch where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecisionMatch where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecisionMatch where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecisionMatch where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecisionMatch where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecisionMatch whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecisionMatch whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
