/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Indexes;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecisionMatch.AdmissionDecisionMatchPath;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerAdmission.CustomerAdmissionPath;
import org.girardsimon.wealthpay.customer.jooq.tables.records.AdmissionDecisionRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdmissionDecision extends TableImpl<AdmissionDecisionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.admission_decision</code>
     */
    public static final AdmissionDecision ADMISSION_DECISION = new AdmissionDecision();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdmissionDecisionRecord> getRecordType() {
        return AdmissionDecisionRecord.class;
    }

    /**
     * The column <code>customer.admission_decision.id</code>.
     */
    public final TableField<AdmissionDecisionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision.idempotency_key</code>.
     */
    public final TableField<AdmissionDecisionRecord, String> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision.policy_version</code>.
     */
    public final TableField<AdmissionDecisionRecord, Long> POLICY_VERSION = createField(DSL.name("policy_version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision.outcome</code>.
     */
    public final TableField<AdmissionDecisionRecord, String> OUTCOME = createField(DSL.name("outcome"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision.subject_type</code>.
     */
    public final TableField<AdmissionDecisionRecord, String> SUBJECT_TYPE = createField(DSL.name("subject_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision.nationalities</code>.
     */
    public final TableField<AdmissionDecisionRecord, String[]> NATIONALITIES = createField(DSL.name("nationalities"), SQLDataType.VARCHAR(2).array(), this, "");

    /**
     * The column <code>customer.admission_decision.country_of_residence</code>.
     */
    public final TableField<AdmissionDecisionRecord, String> COUNTRY_OF_RESIDENCE = createField(DSL.name("country_of_residence"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column
     * <code>customer.admission_decision.country_of_incorporation</code>.
     */
    public final TableField<AdmissionDecisionRecord, String> COUNTRY_OF_INCORPORATION = createField(DSL.name("country_of_incorporation"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>customer.admission_decision.decided_at</code>.
     */
    public final TableField<AdmissionDecisionRecord, OffsetDateTime> DECIDED_AT = createField(DSL.name("decided_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>customer.admission_decision.recorded_at</code>.
     */
    public final TableField<AdmissionDecisionRecord, OffsetDateTime> RECORDED_AT = createField(DSL.name("recorded_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AdmissionDecision(Name alias, Table<AdmissionDecisionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AdmissionDecision(Name alias, Table<AdmissionDecisionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.admission_decision</code> table
     * reference
     */
    public AdmissionDecision(String alias) {
        this(DSL.name(alias), ADMISSION_DECISION);
    }

    /**
     * Create an aliased <code>customer.admission_decision</code> table
     * reference
     */
    public AdmissionDecision(Name alias) {
        this(alias, ADMISSION_DECISION);
    }

    /**
     * Create a <code>customer.admission_decision</code> table reference
     */
    public AdmissionDecision() {
        this(DSL.name("admission_decision"), null);
    }

    public <O extends Record> AdmissionDecision(Table<O> path, ForeignKey<O, AdmissionDecisionRecord> childPath, InverseForeignKey<O, AdmissionDecisionRecord> parentPath) {
        super(path, childPath, parentPath, ADMISSION_DECISION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AdmissionDecisionPath extends AdmissionDecision implements Path<AdmissionDecisionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AdmissionDecisionPath(Table<O> path, ForeignKey<O, AdmissionDecisionRecord> childPath, InverseForeignKey<O, AdmissionDecisionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AdmissionDecisionPath(Name alias, Table<AdmissionDecisionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AdmissionDecisionPath as(String alias) {
            return new AdmissionDecisionPath(DSL.name(alias), this);
        }

        @Override
        public AdmissionDecisionPath as(Name alias) {
            return new AdmissionDecisionPath(alias, this);
        }

        @Override
        public AdmissionDecisionPath as(Table<?> alias) {
            return new AdmissionDecisionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ADMISSION_DECISION_DECIDED_AT, Indexes.IDX_ADMISSION_DECISION_IDEMPOTENCY_KEY);
    }

    @Override
    public UniqueKey<AdmissionDecisionRecord> getPrimaryKey() {
        return Keys.PK_ADMISSION_DECISION;
    }

    @Override
    public List<UniqueKey<AdmissionDecisionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_ADMISSION_DECISION_OUTCOME_SUBJECT);
    }

    private transient AdmissionDecisionMatchPath _admissionDecisionMatch;

    /**
     * Get the implicit to-many join path to the
     * <code>customer.admission_decision_match</code> table
     */
    public AdmissionDecisionMatchPath admissionDecisionMatch() {
        if (_admissionDecisionMatch == null)
            _admissionDecisionMatch = new AdmissionDecisionMatchPath(this, null, Keys.ADMISSION_DECISION_MATCH__FK_ADMISSION_DECISION_MATCH_DECISION.getInverseKey());

        return _admissionDecisionMatch;
    }

    private transient CustomerAdmissionPath _customerAdmission;

    /**
     * Get the implicit to-many join path to the
     * <code>customer.customer_admission</code> table
     */
    public CustomerAdmissionPath customerAdmission() {
        if (_customerAdmission == null)
            _customerAdmission = new CustomerAdmissionPath(this, null, Keys.CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_DECISION.getInverseKey());

        return _customerAdmission;
    }

    @Override
    public List<Check<AdmissionDecisionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_admission_decision_incorporation_shape"), "(((country_of_incorporation IS NULL) OR ((country_of_incorporation)::text ~ '^[A-Z]{2}$'::text)))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_nationalities_shape"), "(((nationalities IS NULL) OR (((array_length(nationalities, 1) >= 1) AND (array_length(nationalities, 1) <= 10)) AND (array_position(nationalities, NULL::character varying) IS NULL) AND (array_to_string(nationalities, ','::text) ~ '^[A-Z]{2}(,[A-Z]{2})*$'::text))))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_outcome_known"), "(((outcome)::text = ANY ((ARRAY['ADMITTED'::character varying, 'REFUSED'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_policy_version_positive"), "((policy_version > 0))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_residence_shape"), "(((country_of_residence IS NULL) OR ((country_of_residence)::text ~ '^[A-Z]{2}$'::text)))", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_subject_columns"), "(\nCASE subject_type\n    WHEN 'INDIVIDUAL'::text THEN ((nationalities IS NOT NULL) AND (country_of_residence IS NOT NULL) AND (country_of_incorporation IS NULL))\n    WHEN 'CORPORATE'::text THEN ((country_of_incorporation IS NOT NULL) AND (nationalities IS NULL) AND (country_of_residence IS NULL))\n    ELSE false\nEND)", true),
            Internal.createCheck(this, DSL.name("ck_admission_decision_subject_type_known"), "(((subject_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'CORPORATE'::character varying])::text[])))", true)
        );
    }

    @Override
    public AdmissionDecision as(String alias) {
        return new AdmissionDecision(DSL.name(alias), this);
    }

    @Override
    public AdmissionDecision as(Name alias) {
        return new AdmissionDecision(alias, this);
    }

    @Override
    public AdmissionDecision as(Table<?> alias) {
        return new AdmissionDecision(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionDecision rename(String name) {
        return new AdmissionDecision(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionDecision rename(Name name) {
        return new AdmissionDecision(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AdmissionDecision rename(Table<?> name) {
        return new AdmissionDecision(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecision where(Condition condition) {
        return new AdmissionDecision(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecision where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecision where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecision where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecision where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecision where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecision where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AdmissionDecision where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecision whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AdmissionDecision whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
