/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.AdmissionDecision.AdmissionDecisionPath;
import org.girardsimon.wealthpay.customer.jooq.tables.Customer.CustomerPath;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerAdmissionRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerAdmission extends TableImpl<CustomerAdmissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.customer_admission</code>
     */
    public static final CustomerAdmission CUSTOMER_ADMISSION = new CustomerAdmission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerAdmissionRecord> getRecordType() {
        return CustomerAdmissionRecord.class;
    }

    /**
     * The column <code>customer.customer_admission.customer_id</code>.
     */
    public final TableField<CustomerAdmissionRecord, UUID> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.customer_admission.decision_id</code>.
     */
    public final TableField<CustomerAdmissionRecord, UUID> DECISION_ID = createField(DSL.name("decision_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.customer_admission.outcome</code>.
     */
    public final TableField<CustomerAdmissionRecord, String> OUTCOME = createField(DSL.name("outcome"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>customer.customer_admission.subject_type</code>.
     */
    public final TableField<CustomerAdmissionRecord, String> SUBJECT_TYPE = createField(DSL.name("subject_type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>customer.customer_admission.linked_at</code>.
     */
    public final TableField<CustomerAdmissionRecord, OffsetDateTime> LINKED_AT = createField(DSL.name("linked_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private CustomerAdmission(Name alias, Table<CustomerAdmissionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerAdmission(Name alias, Table<CustomerAdmissionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.customer_admission</code> table
     * reference
     */
    public CustomerAdmission(String alias) {
        this(DSL.name(alias), CUSTOMER_ADMISSION);
    }

    /**
     * Create an aliased <code>customer.customer_admission</code> table
     * reference
     */
    public CustomerAdmission(Name alias) {
        this(alias, CUSTOMER_ADMISSION);
    }

    /**
     * Create a <code>customer.customer_admission</code> table reference
     */
    public CustomerAdmission() {
        this(DSL.name("customer_admission"), null);
    }

    public <O extends Record> CustomerAdmission(Table<O> path, ForeignKey<O, CustomerAdmissionRecord> childPath, InverseForeignKey<O, CustomerAdmissionRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOMER_ADMISSION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CustomerAdmissionPath extends CustomerAdmission implements Path<CustomerAdmissionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CustomerAdmissionPath(Table<O> path, ForeignKey<O, CustomerAdmissionRecord> childPath, InverseForeignKey<O, CustomerAdmissionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomerAdmissionPath(Name alias, Table<CustomerAdmissionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomerAdmissionPath as(String alias) {
            return new CustomerAdmissionPath(DSL.name(alias), this);
        }

        @Override
        public CustomerAdmissionPath as(Name alias) {
            return new CustomerAdmissionPath(alias, this);
        }

        @Override
        public CustomerAdmissionPath as(Table<?> alias) {
            return new CustomerAdmissionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public UniqueKey<CustomerAdmissionRecord> getPrimaryKey() {
        return Keys.PK_CUSTOMER_ADMISSION;
    }

    @Override
    public List<UniqueKey<CustomerAdmissionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_CUSTOMER_ADMISSION_DECISION);
    }

    @Override
    public List<ForeignKey<CustomerAdmissionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_CUSTOMER, Keys.CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_DECISION);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>customer.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_CUSTOMER, null);

        return _customer;
    }

    private transient AdmissionDecisionPath _admissionDecision;

    /**
     * Get the implicit join path to the
     * <code>customer.admission_decision</code> table.
     */
    public AdmissionDecisionPath admissionDecision() {
        if (_admissionDecision == null)
            _admissionDecision = new AdmissionDecisionPath(this, Keys.CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_DECISION, null);

        return _admissionDecision;
    }

    @Override
    public List<Check<CustomerAdmissionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_customer_admission_admitted_only"), "(((outcome)::text = 'ADMITTED'::text))", true),
            Internal.createCheck(this, DSL.name("ck_customer_admission_subject_type_known"), "(((subject_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'CORPORATE'::character varying])::text[])))", true)
        );
    }

    @Override
    public CustomerAdmission as(String alias) {
        return new CustomerAdmission(DSL.name(alias), this);
    }

    @Override
    public CustomerAdmission as(Name alias) {
        return new CustomerAdmission(alias, this);
    }

    @Override
    public CustomerAdmission as(Table<?> alias) {
        return new CustomerAdmission(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerAdmission rename(String name) {
        return new CustomerAdmission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerAdmission rename(Name name) {
        return new CustomerAdmission(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerAdmission rename(Table<?> name) {
        return new CustomerAdmission(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerAdmission where(Condition condition) {
        return new CustomerAdmission(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerAdmission where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerAdmission where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerAdmission where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerAdmission where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerAdmission where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerAdmission where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerAdmission where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerAdmission whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerAdmission whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
