/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.Customer.CustomerPath;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerStatusTransitionRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerStatusTransition extends TableImpl<CustomerStatusTransitionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>customer.customer_status_transition</code>
     */
    public static final CustomerStatusTransition CUSTOMER_STATUS_TRANSITION = new CustomerStatusTransition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerStatusTransitionRecord> getRecordType() {
        return CustomerStatusTransitionRecord.class;
    }

    /**
     * The column <code>customer.customer_status_transition.customer_id</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, UUID> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.customer_status_transition.sequence_no</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, Integer> SEQUENCE_NO = createField(DSL.name("sequence_no"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>customer.customer_status_transition.from_status</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, String> FROM_STATUS = createField(DSL.name("from_status"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>customer.customer_status_transition.to_status</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, String> TO_STATUS = createField(DSL.name("to_status"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>customer.customer_status_transition.occurred_at</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, OffsetDateTime> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>customer.customer_status_transition.recorded_at</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, OffsetDateTime> RECORDED_AT = createField(DSL.name("recorded_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>customer.customer_status_transition.actor</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, String> ACTOR = createField(DSL.name("actor"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>customer.customer_status_transition.reason</code>.
     */
    public final TableField<CustomerStatusTransitionRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.CLOB, this, "");

    private CustomerStatusTransition(Name alias, Table<CustomerStatusTransitionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerStatusTransition(Name alias, Table<CustomerStatusTransitionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.customer_status_transition</code> table
     * reference
     */
    public CustomerStatusTransition(String alias) {
        this(DSL.name(alias), CUSTOMER_STATUS_TRANSITION);
    }

    /**
     * Create an aliased <code>customer.customer_status_transition</code> table
     * reference
     */
    public CustomerStatusTransition(Name alias) {
        this(alias, CUSTOMER_STATUS_TRANSITION);
    }

    /**
     * Create a <code>customer.customer_status_transition</code> table reference
     */
    public CustomerStatusTransition() {
        this(DSL.name("customer_status_transition"), null);
    }

    public <O extends Record> CustomerStatusTransition(Table<O> path, ForeignKey<O, CustomerStatusTransitionRecord> childPath, InverseForeignKey<O, CustomerStatusTransitionRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOMER_STATUS_TRANSITION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CustomerStatusTransitionPath extends CustomerStatusTransition implements Path<CustomerStatusTransitionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CustomerStatusTransitionPath(Table<O> path, ForeignKey<O, CustomerStatusTransitionRecord> childPath, InverseForeignKey<O, CustomerStatusTransitionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomerStatusTransitionPath(Name alias, Table<CustomerStatusTransitionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomerStatusTransitionPath as(String alias) {
            return new CustomerStatusTransitionPath(DSL.name(alias), this);
        }

        @Override
        public CustomerStatusTransitionPath as(Name alias) {
            return new CustomerStatusTransitionPath(alias, this);
        }

        @Override
        public CustomerStatusTransitionPath as(Table<?> alias) {
            return new CustomerStatusTransitionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public UniqueKey<CustomerStatusTransitionRecord> getPrimaryKey() {
        return Keys.PK_CUSTOMER_STATUS_TRANSITION;
    }

    @Override
    public List<ForeignKey<CustomerStatusTransitionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CUSTOMER_STATUS_TRANSITION__FK_CUSTOMER_STATUS_TRANSITION_CUSTOMER);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>customer.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.CUSTOMER_STATUS_TRANSITION__FK_CUSTOMER_STATUS_TRANSITION_CUSTOMER, null);

        return _customer;
    }

    @Override
    public List<Check<CustomerStatusTransitionRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_customer_status_transition_actor_present"), "((actor <> ''::text))", true),
            Internal.createCheck(this, DSL.name("ck_customer_status_transition_changes_status"), "(((from_status)::text <> (to_status)::text))", true),
            Internal.createCheck(this, DSL.name("ck_customer_status_transition_from_known"), "(((from_status)::text = ANY ((ARRAY['ONBOARDING'::character varying, 'ACTIVE'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_customer_status_transition_sequence_positive"), "((sequence_no >= 1))", true),
            Internal.createCheck(this, DSL.name("ck_customer_status_transition_starts_from_onboarding"), "(((sequence_no > 1) OR ((from_status)::text = 'ONBOARDING'::text)))", true),
            Internal.createCheck(this, DSL.name("ck_customer_status_transition_to_known"), "(((to_status)::text = ANY ((ARRAY['ONBOARDING'::character varying, 'ACTIVE'::character varying])::text[])))", true)
        );
    }

    @Override
    public CustomerStatusTransition as(String alias) {
        return new CustomerStatusTransition(DSL.name(alias), this);
    }

    @Override
    public CustomerStatusTransition as(Name alias) {
        return new CustomerStatusTransition(alias, this);
    }

    @Override
    public CustomerStatusTransition as(Table<?> alias) {
        return new CustomerStatusTransition(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerStatusTransition rename(String name) {
        return new CustomerStatusTransition(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerStatusTransition rename(Name name) {
        return new CustomerStatusTransition(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerStatusTransition rename(Table<?> name) {
        return new CustomerStatusTransition(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerStatusTransition where(Condition condition) {
        return new CustomerStatusTransition(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerStatusTransition where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerStatusTransition where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerStatusTransition where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerStatusTransition where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerStatusTransition where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerStatusTransition where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerStatusTransition where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerStatusTransition whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerStatusTransition whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
