/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerAdmission.CustomerAdmissionPath;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerNationality.CustomerNationalityPath;
import org.girardsimon.wealthpay.customer.jooq.tables.CustomerStatusTransition.CustomerStatusTransitionPath;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Customer extends TableImpl<CustomerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.customer</code>
     */
    public static final Customer CUSTOMER_ = new Customer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerRecord> getRecordType() {
        return CustomerRecord.class;
    }

    /**
     * The column <code>customer.customer.id</code>.
     */
    public final TableField<CustomerRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.customer.customer_number</code>.
     */
    public final TableField<CustomerRecord, String> CUSTOMER_NUMBER = createField(DSL.name("customer_number"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>customer.customer.email</code>.
     */
    public final TableField<CustomerRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(254).nullable(false), this, "");

    /**
     * The column <code>customer.customer.status</code>.
     */
    public final TableField<CustomerRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>customer.customer.registered_at</code>.
     */
    public final TableField<CustomerRecord, OffsetDateTime> REGISTERED_AT = createField(DSL.name("registered_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>customer.customer.activated_at</code>.
     */
    public final TableField<CustomerRecord, OffsetDateTime> ACTIVATED_AT = createField(DSL.name("activated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>customer.customer.kind</code>.
     */
    public final TableField<CustomerRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>customer.customer.given_name</code>.
     */
    public final TableField<CustomerRecord, String> GIVEN_NAME = createField(DSL.name("given_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>customer.customer.middle_name</code>.
     */
    public final TableField<CustomerRecord, String> MIDDLE_NAME = createField(DSL.name("middle_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>customer.customer.family_name</code>.
     */
    public final TableField<CustomerRecord, String> FAMILY_NAME = createField(DSL.name("family_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>customer.customer.date_of_birth</code>.
     */
    public final TableField<CustomerRecord, LocalDate> DATE_OF_BIRTH = createField(DSL.name("date_of_birth"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>customer.customer.gender</code>.
     */
    public final TableField<CustomerRecord, String> GENDER = createField(DSL.name("gender"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>customer.customer.country_of_residence</code>.
     */
    public final TableField<CustomerRecord, String> COUNTRY_OF_RESIDENCE = createField(DSL.name("country_of_residence"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>customer.customer.registered_name</code>.
     */
    public final TableField<CustomerRecord, String> REGISTERED_NAME = createField(DSL.name("registered_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>customer.customer.registration_number</code>.
     */
    public final TableField<CustomerRecord, String> REGISTRATION_NUMBER = createField(DSL.name("registration_number"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>customer.customer.country_of_incorporation</code>.
     */
    public final TableField<CustomerRecord, String> COUNTRY_OF_INCORPORATION = createField(DSL.name("country_of_incorporation"), SQLDataType.VARCHAR(2), this, "");

    private Customer(Name alias, Table<CustomerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Customer(Name alias, Table<CustomerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.customer</code> table reference
     */
    public Customer(String alias) {
        this(DSL.name(alias), CUSTOMER_);
    }

    /**
     * Create an aliased <code>customer.customer</code> table reference
     */
    public Customer(Name alias) {
        this(alias, CUSTOMER_);
    }

    /**
     * Create a <code>customer.customer</code> table reference
     */
    public Customer() {
        this(DSL.name("customer"), null);
    }

    public <O extends Record> Customer(Table<O> path, ForeignKey<O, CustomerRecord> childPath, InverseForeignKey<O, CustomerRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOMER_);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CustomerPath extends Customer implements Path<CustomerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CustomerPath(Table<O> path, ForeignKey<O, CustomerRecord> childPath, InverseForeignKey<O, CustomerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomerPath(Name alias, Table<CustomerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomerPath as(String alias) {
            return new CustomerPath(DSL.name(alias), this);
        }

        @Override
        public CustomerPath as(Name alias) {
            return new CustomerPath(alias, this);
        }

        @Override
        public CustomerPath as(Table<?> alias) {
            return new CustomerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : org.girardsimon.wealthpay.customer.jooq.Customer.CUSTOMER;
    }

    @Override
    public UniqueKey<CustomerRecord> getPrimaryKey() {
        return Keys.PK_CUSTOMER;
    }

    @Override
    public List<UniqueKey<CustomerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_CUSTOMER_EMAIL, Keys.UQ_CUSTOMER_ID_KIND, Keys.UQ_CUSTOMER_NUMBER);
    }

    private transient CustomerAdmissionPath _customerAdmission;

    /**
     * Get the implicit to-many join path to the
     * <code>customer.customer_admission</code> table
     */
    public CustomerAdmissionPath customerAdmission() {
        if (_customerAdmission == null)
            _customerAdmission = new CustomerAdmissionPath(this, null, Keys.CUSTOMER_ADMISSION__FK_CUSTOMER_ADMISSION_CUSTOMER.getInverseKey());

        return _customerAdmission;
    }

    private transient CustomerNationalityPath _customerNationality;

    /**
     * Get the implicit to-many join path to the
     * <code>customer.customer_nationality</code> table
     */
    public CustomerNationalityPath customerNationality() {
        if (_customerNationality == null)
            _customerNationality = new CustomerNationalityPath(this, null, Keys.CUSTOMER_NATIONALITY__FK_CUSTOMER_NATIONALITY_CUSTOMER.getInverseKey());

        return _customerNationality;
    }

    private transient CustomerStatusTransitionPath _customerStatusTransition;

    /**
     * Get the implicit to-many join path to the
     * <code>customer.customer_status_transition</code> table
     */
    public CustomerStatusTransitionPath customerStatusTransition() {
        if (_customerStatusTransition == null)
            _customerStatusTransition = new CustomerStatusTransitionPath(this, null, Keys.CUSTOMER_STATUS_TRANSITION__FK_CUSTOMER_STATUS_TRANSITION_CUSTOMER.getInverseKey());

        return _customerStatusTransition;
    }

    @Override
    public List<Check<CustomerRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_customer_activation_not_before_registration"), "(((activated_at IS NULL) OR (activated_at >= registered_at)))", true),
            Internal.createCheck(this, DSL.name("ck_customer_active_iff_activated"), "((((status)::text = 'ACTIVE'::text) = (activated_at IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("ck_customer_date_of_birth_plausible"), "(((date_of_birth IS NULL) OR ((date_of_birth >= '1900-01-01'::date) AND (date_of_birth <= '2100-01-01'::date))))", true),
            Internal.createCheck(this, DSL.name("ck_customer_email_canonical"), "(((email)::text = lower((email)::text)))", true),
            Internal.createCheck(this, DSL.name("ck_customer_gender_known"), "(((gender IS NULL) OR ((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'UNSPECIFIED'::character varying])::text[]))))", true),
            Internal.createCheck(this, DSL.name("ck_customer_incorporation_shape"), "(((country_of_incorporation IS NULL) OR ((country_of_incorporation)::text ~ '^[A-Z]{2}$'::text)))", true),
            Internal.createCheck(this, DSL.name("ck_customer_kind_known"), "(((kind)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'CORPORATE'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_customer_number_shape"), "(((customer_number)::text ~ '^[0-9]{10}$'::text))", true),
            Internal.createCheck(this, DSL.name("ck_customer_required_text_not_blank"), "((((given_name IS NULL) OR (btrim(given_name) <> ''::text)) AND ((family_name IS NULL) OR (btrim(family_name) <> ''::text)) AND ((registered_name IS NULL) OR (btrim(registered_name) <> ''::text)) AND ((registration_number IS NULL) OR (btrim(registration_number) <> ''::text))))", true),
            Internal.createCheck(this, DSL.name("ck_customer_residence_shape"), "(((country_of_residence IS NULL) OR ((country_of_residence)::text ~ '^[A-Z]{2}$'::text)))", true),
            Internal.createCheck(this, DSL.name("ck_customer_status_known"), "(((status)::text = ANY ((ARRAY['ONBOARDING'::character varying, 'ACTIVE'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_customer_subtype_columns"), "(\nCASE kind\n    WHEN 'INDIVIDUAL'::text THEN ((given_name IS NOT NULL) AND (family_name IS NOT NULL) AND (date_of_birth IS NOT NULL) AND (gender IS NOT NULL) AND (country_of_residence IS NOT NULL) AND (registered_name IS NULL) AND (registration_number IS NULL) AND (country_of_incorporation IS NULL))\n    WHEN 'CORPORATE'::text THEN ((registered_name IS NOT NULL) AND (registration_number IS NOT NULL) AND (country_of_incorporation IS NOT NULL) AND (given_name IS NULL) AND (middle_name IS NULL) AND (family_name IS NULL) AND (date_of_birth IS NULL) AND (gender IS NULL) AND (country_of_residence IS NULL))\n    ELSE false\nEND)", true)
        );
    }

    @Override
    public Customer as(String alias) {
        return new Customer(DSL.name(alias), this);
    }

    @Override
    public Customer as(Name alias) {
        return new Customer(alias, this);
    }

    @Override
    public Customer as(Table<?> alias) {
        return new Customer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(String name) {
        return new Customer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(Name name) {
        return new Customer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Customer rename(Table<?> name) {
        return new Customer(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customer where(Condition condition) {
        return new Customer(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customer where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customer where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customer where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customer where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customer where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customer where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Customer where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customer whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Customer whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
