/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Indexes;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.Customer.CustomerPath;
import org.girardsimon.wealthpay.customer.jooq.tables.records.CustomerNationalityRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerNationality extends TableImpl<CustomerNationalityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.customer_nationality</code>
     */
    public static final CustomerNationality CUSTOMER_NATIONALITY = new CustomerNationality();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerNationalityRecord> getRecordType() {
        return CustomerNationalityRecord.class;
    }

    /**
     * The column <code>customer.customer_nationality.customer_id</code>.
     */
    public final TableField<CustomerNationalityRecord, UUID> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.customer_nationality.kind</code>.
     */
    public final TableField<CustomerNationalityRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>customer.customer_nationality.country_code</code>.
     */
    public final TableField<CustomerNationalityRecord, String> COUNTRY_CODE = createField(DSL.name("country_code"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    private CustomerNationality(Name alias, Table<CustomerNationalityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CustomerNationality(Name alias, Table<CustomerNationalityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.customer_nationality</code> table
     * reference
     */
    public CustomerNationality(String alias) {
        this(DSL.name(alias), CUSTOMER_NATIONALITY);
    }

    /**
     * Create an aliased <code>customer.customer_nationality</code> table
     * reference
     */
    public CustomerNationality(Name alias) {
        this(alias, CUSTOMER_NATIONALITY);
    }

    /**
     * Create a <code>customer.customer_nationality</code> table reference
     */
    public CustomerNationality() {
        this(DSL.name("customer_nationality"), null);
    }

    public <O extends Record> CustomerNationality(Table<O> path, ForeignKey<O, CustomerNationalityRecord> childPath, InverseForeignKey<O, CustomerNationalityRecord> parentPath) {
        super(path, childPath, parentPath, CUSTOMER_NATIONALITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CustomerNationalityPath extends CustomerNationality implements Path<CustomerNationalityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CustomerNationalityPath(Table<O> path, ForeignKey<O, CustomerNationalityRecord> childPath, InverseForeignKey<O, CustomerNationalityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CustomerNationalityPath(Name alias, Table<CustomerNationalityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CustomerNationalityPath as(String alias) {
            return new CustomerNationalityPath(DSL.name(alias), this);
        }

        @Override
        public CustomerNationalityPath as(Name alias) {
            return new CustomerNationalityPath(alias, this);
        }

        @Override
        public CustomerNationalityPath as(Table<?> alias) {
            return new CustomerNationalityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CUSTOMER_NATIONALITY_COUNTRY_CODE);
    }

    @Override
    public UniqueKey<CustomerNationalityRecord> getPrimaryKey() {
        return Keys.PK_CUSTOMER_NATIONALITY;
    }

    @Override
    public List<ForeignKey<CustomerNationalityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CUSTOMER_NATIONALITY__FK_CUSTOMER_NATIONALITY_CUSTOMER);
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>customer.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.CUSTOMER_NATIONALITY__FK_CUSTOMER_NATIONALITY_CUSTOMER, null);

        return _customer;
    }

    @Override
    public List<Check<CustomerNationalityRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_customer_nationality_country_shape"), "(((country_code)::text ~ '^[A-Z]{2}$'::text))", true),
            Internal.createCheck(this, DSL.name("ck_customer_nationality_individuals_only"), "(((kind)::text = 'INDIVIDUAL'::text))", true)
        );
    }

    @Override
    public CustomerNationality as(String alias) {
        return new CustomerNationality(DSL.name(alias), this);
    }

    @Override
    public CustomerNationality as(Name alias) {
        return new CustomerNationality(alias, this);
    }

    @Override
    public CustomerNationality as(Table<?> alias) {
        return new CustomerNationality(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerNationality rename(String name) {
        return new CustomerNationality(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerNationality rename(Name name) {
        return new CustomerNationality(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerNationality rename(Table<?> name) {
        return new CustomerNationality(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerNationality where(Condition condition) {
        return new CustomerNationality(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerNationality where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerNationality where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerNationality where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerNationality where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerNationality where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerNationality where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CustomerNationality where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerNationality whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CustomerNationality whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
