/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.records.LicensedCountryRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LicensedCountry extends TableImpl<LicensedCountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.licensed_country</code>
     */
    public static final LicensedCountry LICENSED_COUNTRY = new LicensedCountry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LicensedCountryRecord> getRecordType() {
        return LicensedCountryRecord.class;
    }

    /**
     * The column <code>customer.licensed_country.country_code</code>.
     */
    public final TableField<LicensedCountryRecord, String> COUNTRY_CODE = createField(DSL.name("country_code"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>customer.licensed_country.connecting_factor</code>.
     */
    public final TableField<LicensedCountryRecord, String> CONNECTING_FACTOR = createField(DSL.name("connecting_factor"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private LicensedCountry(Name alias, Table<LicensedCountryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LicensedCountry(Name alias, Table<LicensedCountryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.licensed_country</code> table reference
     */
    public LicensedCountry(String alias) {
        this(DSL.name(alias), LICENSED_COUNTRY);
    }

    /**
     * Create an aliased <code>customer.licensed_country</code> table reference
     */
    public LicensedCountry(Name alias) {
        this(alias, LICENSED_COUNTRY);
    }

    /**
     * Create a <code>customer.licensed_country</code> table reference
     */
    public LicensedCountry() {
        this(DSL.name("licensed_country"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public UniqueKey<LicensedCountryRecord> getPrimaryKey() {
        return Keys.PK_LICENSED_COUNTRY;
    }

    @Override
    public List<Check<LicensedCountryRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_licensed_country_code_shape"), "(((country_code)::text ~ '^[A-Z]{2}$'::text))", true),
            Internal.createCheck(this, DSL.name("ck_licensed_country_factor_known"), "(((connecting_factor)::text = ANY ((ARRAY['RESIDENCE'::character varying, 'INCORPORATION'::character varying])::text[])))", true)
        );
    }

    @Override
    public LicensedCountry as(String alias) {
        return new LicensedCountry(DSL.name(alias), this);
    }

    @Override
    public LicensedCountry as(Name alias) {
        return new LicensedCountry(alias, this);
    }

    @Override
    public LicensedCountry as(Table<?> alias) {
        return new LicensedCountry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LicensedCountry rename(String name) {
        return new LicensedCountry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LicensedCountry rename(Name name) {
        return new LicensedCountry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LicensedCountry rename(Table<?> name) {
        return new LicensedCountry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LicensedCountry where(Condition condition) {
        return new LicensedCountry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LicensedCountry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LicensedCountry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LicensedCountry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LicensedCountry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LicensedCountry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LicensedCountry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LicensedCountry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LicensedCountry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LicensedCountry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
