/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.records.ProcessedRegistrationsRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessedRegistrations extends TableImpl<ProcessedRegistrationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.processed_registrations</code>
     */
    public static final ProcessedRegistrations PROCESSED_REGISTRATIONS = new ProcessedRegistrations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProcessedRegistrationsRecord> getRecordType() {
        return ProcessedRegistrationsRecord.class;
    }

    /**
     * The column <code>customer.processed_registrations.idempotency_key</code>.
     */
    public final TableField<ProcessedRegistrationsRecord, String> IDEMPOTENCY_KEY = createField(DSL.name("idempotency_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>customer.processed_registrations.fingerprint</code>.
     */
    public final TableField<ProcessedRegistrationsRecord, String> FINGERPRINT = createField(DSL.name("fingerprint"), SQLDataType.CHAR(64).nullable(false), this, "");

    /**
     * The column <code>customer.processed_registrations.customer_id</code>.
     */
    public final TableField<ProcessedRegistrationsRecord, UUID> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>customer.processed_registrations.occurred_at</code>.
     */
    public final TableField<ProcessedRegistrationsRecord, OffsetDateTime> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private ProcessedRegistrations(Name alias, Table<ProcessedRegistrationsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ProcessedRegistrations(Name alias, Table<ProcessedRegistrationsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.processed_registrations</code> table
     * reference
     */
    public ProcessedRegistrations(String alias) {
        this(DSL.name(alias), PROCESSED_REGISTRATIONS);
    }

    /**
     * Create an aliased <code>customer.processed_registrations</code> table
     * reference
     */
    public ProcessedRegistrations(Name alias) {
        this(alias, PROCESSED_REGISTRATIONS);
    }

    /**
     * Create a <code>customer.processed_registrations</code> table reference
     */
    public ProcessedRegistrations() {
        this(DSL.name("processed_registrations"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public UniqueKey<ProcessedRegistrationsRecord> getPrimaryKey() {
        return Keys.PK_PROCESSED_REGISTRATIONS;
    }

    @Override
    public List<Check<ProcessedRegistrationsRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_processed_registrations_fingerprint_shape"), "((fingerprint ~ '^[0-9a-f]{64}$'::text))", true)
        );
    }

    @Override
    public ProcessedRegistrations as(String alias) {
        return new ProcessedRegistrations(DSL.name(alias), this);
    }

    @Override
    public ProcessedRegistrations as(Name alias) {
        return new ProcessedRegistrations(alias, this);
    }

    @Override
    public ProcessedRegistrations as(Table<?> alias) {
        return new ProcessedRegistrations(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedRegistrations rename(String name) {
        return new ProcessedRegistrations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedRegistrations rename(Name name) {
        return new ProcessedRegistrations(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProcessedRegistrations rename(Table<?> name) {
        return new ProcessedRegistrations(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedRegistrations where(Condition condition) {
        return new ProcessedRegistrations(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedRegistrations where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedRegistrations where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedRegistrations where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedRegistrations where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedRegistrations where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedRegistrations where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ProcessedRegistrations where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedRegistrations whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ProcessedRegistrations whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
