/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.customer.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.girardsimon.wealthpay.customer.jooq.Customer;
import org.girardsimon.wealthpay.customer.jooq.Keys;
import org.girardsimon.wealthpay.customer.jooq.tables.records.RestrictedCountryRecord;
import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RestrictedCountry extends TableImpl<RestrictedCountryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>customer.restricted_country</code>
     */
    public static final RestrictedCountry RESTRICTED_COUNTRY = new RestrictedCountry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RestrictedCountryRecord> getRecordType() {
        return RestrictedCountryRecord.class;
    }

    /**
     * The column <code>customer.restricted_country.country_code</code>.
     */
    public final TableField<RestrictedCountryRecord, String> COUNTRY_CODE = createField(DSL.name("country_code"), SQLDataType.VARCHAR(2).nullable(false), this, "");

    /**
     * The column <code>customer.restricted_country.restriction</code>.
     */
    public final TableField<RestrictedCountryRecord, String> RESTRICTION = createField(DSL.name("restriction"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>customer.restricted_country.connecting_factor</code>.
     */
    public final TableField<RestrictedCountryRecord, String> CONNECTING_FACTOR = createField(DSL.name("connecting_factor"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    private RestrictedCountry(Name alias, Table<RestrictedCountryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RestrictedCountry(Name alias, Table<RestrictedCountryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>customer.restricted_country</code> table
     * reference
     */
    public RestrictedCountry(String alias) {
        this(DSL.name(alias), RESTRICTED_COUNTRY);
    }

    /**
     * Create an aliased <code>customer.restricted_country</code> table
     * reference
     */
    public RestrictedCountry(Name alias) {
        this(alias, RESTRICTED_COUNTRY);
    }

    /**
     * Create a <code>customer.restricted_country</code> table reference
     */
    public RestrictedCountry() {
        this(DSL.name("restricted_country"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Customer.CUSTOMER;
    }

    @Override
    public UniqueKey<RestrictedCountryRecord> getPrimaryKey() {
        return Keys.PK_RESTRICTED_COUNTRY;
    }

    @Override
    public List<Check<RestrictedCountryRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_restricted_country_code_shape"), "(((country_code)::text ~ '^[A-Z]{2}$'::text))", true),
            Internal.createCheck(this, DSL.name("ck_restricted_country_factor_known"), "(((connecting_factor)::text = ANY ((ARRAY['NATIONALITY'::character varying, 'RESIDENCE'::character varying, 'INCORPORATION'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("ck_restricted_country_restriction_known"), "(((restriction)::text = ANY ((ARRAY['SANCTIONED'::character varying, 'RESTRICTED_PERSON'::character varying])::text[])))", true)
        );
    }

    @Override
    public RestrictedCountry as(String alias) {
        return new RestrictedCountry(DSL.name(alias), this);
    }

    @Override
    public RestrictedCountry as(Name alias) {
        return new RestrictedCountry(alias, this);
    }

    @Override
    public RestrictedCountry as(Table<?> alias) {
        return new RestrictedCountry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RestrictedCountry rename(String name) {
        return new RestrictedCountry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RestrictedCountry rename(Name name) {
        return new RestrictedCountry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RestrictedCountry rename(Table<?> name) {
        return new RestrictedCountry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestrictedCountry where(Condition condition) {
        return new RestrictedCountry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestrictedCountry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestrictedCountry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestrictedCountry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestrictedCountry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestrictedCountry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestrictedCountry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RestrictedCountry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestrictedCountry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RestrictedCountry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
