openapi: 3.1.0
info:
  title: WealthPay Account API
  version: 1.0.0
  description: API pour la gestion des comptes dans WealthPay (monolithe modulaire).

servers:
  - url: http://localhost:8080
    description: Local dev

paths:
  /accounts:
    post:
      summary: Ouvrir un nouveau compte
      operationId: openAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenAccountRequest'
      responses:
        '200':
          description: Compte créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenAccountResponse'
        '400':
          description: Requête invalide

  /accounts/{id}:
    get:
      summary: Obtenir les détails d'un compte
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique du compte (UUID)
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Compte trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Compte introuvable

components:
  schemas:
    OpenAccountRequest:
      type: object
      required:
        - currency
        - initialBalance
      properties:
        currency:
          type: string
          description: Code ISO de la devise (ex. CHF, EUR)
          minLength: 3
          maxLength: 3
        initialBalance:
          type: number
          format: double
          description: Solde initial du compte, doit être >= 0
          minimum: 0

    OpenAccountResponse:
      type: object
      required:
        - accountId
      properties:
        accountId:
          type: string
          format: uuid
          description: Identifiant unique du compte créé

    AccountResponse:
      type: object
      required:
        - id
        - currency
        - balance
      properties:
        id:
          type: string
          format: uuid
        currency:
          type: string
          minLength: 3
          maxLength: 3
        balance:
          type: number
          format: double